#!/usr/bin/env python3
"""
Gemma Story Generator - Robust pipeline for generating traditional adult stories.

CONTRACT: This script is infrastructure only. All story prose is generated by Gemma-7B.
Claude/humans must NOT write any story prose.

Usage:
    python3 generate_story.py --story-id 301 --mood joyful
    python3 generate_story.py --story-id 301 --mood joyful --theme "finding joy in simple things"
    python3 generate_story.py --batch  # Generate all 8 moods starting at ID 301
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# === CONFIGURATION ===

MODEL = "gemma:7b"
OLLAMA_URL = "http://localhost:11434/api/generate"
NUM_PREDICT = 2600
TEMPERATURE = 0.4
STOP_TOKEN = "<END>"

MIN_WORDS = 510
MAX_WORDS = 680
MIN_PARAGRAPHS = 12
MAX_PARAGRAPHS = 12
MIN_SENTENCES_PER_PARA = 4
MAX_SENTENCES_PER_PARA = 6

MAX_RETRIES = 3

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
STORIES_DIR = PROJECT_ROOT / "assets" / "stories"
QUARANTINE_DIR = STORIES_DIR / "_invalid"

# Abbreviations to exclude from sentence splitting
ABBREVIATIONS = {"Mr.", "Mrs.", "Ms.", "Dr.", "St.", "vs.", "etc.", "e.g.", "i.e.", "Jr.", "Sr."}

# Mood to theme mapping (default themes if not specified)
DEFAULT_THEMES = {
    "joyful": "gratitude and celebration",
    "weary": "rest and perseverance",
    "anxious": "peace amid worry",
    "hurting": "comfort in grief",
    "neutral": "quiet reflection",
    "encouraging": "hope and strength",
    "calm_peaceful": "serenity and rest",
    "brave_courage": "courage and faith",
}

# === PROMPT TEMPLATE ===

PROMPT_TEMPLATE = """You are a calm, reverent storyteller creating a spoken devotional-style story rooted in Christian values.

Write one story with the following constraints:
- Audience: Adult
- Mode: Traditional (like a pastoral reflection)
- Mood: {mood}
- Theme: {theme}
- Length: ~600 words (5 minutes spoken)
- Tone: calm, reverent, pastoral, spoken narrative

STYLE RULES (MANDATORY):
- No modern slang
- No fantasy elements or fictional worlds
- No headings, numbering, or bullet points
- No long scripture quotations (short allusions are fine)
- Written as spoken narrative, not poetry

STRUCTURE RULES (MANDATORY - FOLLOW EXACTLY):
- Write EXACTLY 12 paragraphs
- Each paragraph must have EXACTLY 5 sentences
- Each sentence should average 10-12 words
- Separate paragraphs with a blank line
- After the final sentence of paragraph 12, output the token <END> and nothing else
- Do NOT stop early
- Do NOT add any text after <END>

PURPOSE:
The story should feel like something a trusted pastor or mentor would gently speak to someone feeling {mood}.

Begin the story now. Write all 12 paragraphs, each with exactly 5 sentences, then output <END>."""


# === HELPER FUNCTIONS ===

def count_words(text: str) -> int:
    """Count words in text."""
    return len(text.split())


def split_paragraphs(text: str) -> list[str]:
    """Split text into paragraphs (separated by blank lines)."""
    paragraphs = [p.strip() for p in re.split(r'\n\s*\n', text.strip()) if p.strip()]
    return paragraphs


def count_sentences(paragraph: str) -> int:
    """
    Count sentences in a paragraph using simple heuristics.
    Splits on .?! followed by whitespace or end-of-string.
    Excludes common abbreviations.
    """
    # Replace abbreviations with placeholders to avoid false splits
    temp = paragraph
    for abbr in ABBREVIATIONS:
        temp = temp.replace(abbr, abbr.replace(".", "###DOT###"))

    # Split on sentence-ending punctuation
    # Match .?! followed by whitespace, quote+whitespace, or end of string
    sentences = re.split(r'[.?!](?:\s|"|\'\s|$)', temp)

    # Filter out empty strings
    sentences = [s.strip() for s in sentences if s.strip()]

    return len(sentences)


def detect_headings_or_bullets(text: str) -> bool:
    """Check if text contains headings, numbering, or bullet points."""
    lines = text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Check for numbered lines like "1." or "1)"
        if re.match(r'^\d+[.)]\s', line):
            return True
        # Check for bullet points
        if re.match(r'^[-*•]\s', line):
            return True
        # Check for markdown headers
        if re.match(r'^#+\s', line):
            return True
    return False


def validate_story(text: str) -> tuple[bool, list[str]]:
    """
    Validate story structure and content.
    Returns (is_valid, list_of_errors).
    """
    errors = []

    # Check word count
    word_count = count_words(text)
    if word_count < MIN_WORDS:
        errors.append(f"Word count too low: {word_count} < {MIN_WORDS}")
    if word_count > MAX_WORDS:
        errors.append(f"Word count too high: {word_count} > {MAX_WORDS}")

    # Check paragraph count
    paragraphs = split_paragraphs(text)
    para_count = len(paragraphs)
    if para_count != MIN_PARAGRAPHS:
        errors.append(f"Paragraph count wrong: {para_count} != {MIN_PARAGRAPHS}")

    # Check sentences per paragraph (tolerant: 4-6)
    for i, para in enumerate(paragraphs):
        sent_count = count_sentences(para)
        if sent_count < MIN_SENTENCES_PER_PARA or sent_count > MAX_SENTENCES_PER_PARA:
            errors.append(f"Paragraph {i+1} has {sent_count} sentences (expected {MIN_SENTENCES_PER_PARA}-{MAX_SENTENCES_PER_PARA})")

    # Check for headings/bullets
    if detect_headings_or_bullets(text):
        errors.append("Contains headings, numbering, or bullet points")

    return (len(errors) == 0, errors)


def create_header(story_id: str, mood: str, word_count: int) -> str:
    """Create the mechanical header (not generated by Gemma)."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"""ID: parable_{story_id}
Mood: {mood}
Audience: adult
Mode: traditional
Length: 5min
WordTarget: 600
WordCount: {word_count}
Source: gemma:7b (ollama)
GeneratedAt: {timestamp}
"""


def call_ollama(prompt: str) -> tuple[str, bool]:
    """
    Call Ollama API and return (response_text, success).
    """
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "num_predict": NUM_PREDICT,
            "temperature": TEMPERATURE,
        },
        "stop": [STOP_TOKEN],
    }

    try:
        result = subprocess.run(
            ["curl", "-s", "-X", "POST", OLLAMA_URL,
             "-H", "Content-Type: application/json",
             "-d", json.dumps(payload)],
            capture_output=True,
            text=True,
            timeout=300
        )

        if result.returncode != 0:
            print(f"  ERROR: curl failed with code {result.returncode}")
            return "", False

        response = json.loads(result.stdout)
        text = response.get("response", "")
        return text, True

    except subprocess.TimeoutExpired:
        print("  ERROR: Ollama request timed out")
        return "", False
    except json.JSONDecodeError as e:
        print(f"  ERROR: Failed to parse Ollama response: {e}")
        return "", False
    except Exception as e:
        print(f"  ERROR: Unexpected error calling Ollama: {e}")
        return "", False


def process_output(raw_text: str) -> tuple[str, bool]:
    """
    Process raw Gemma output:
    - Truncate at <END> if present
    - Remove <END> token from final text
    Returns (processed_text, had_end_token).
    """
    if STOP_TOKEN in raw_text:
        # Truncate at <END> and remove the token
        text = raw_text.split(STOP_TOKEN)[0].strip()
        return text, True
    else:
        # No <END> token found
        return raw_text.strip(), False


def quarantine_file(filepath: Path, reason: str):
    """Move file to quarantine directory with reason."""
    QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)

    # Add timestamp to avoid collisions
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    quarantine_name = f"{filepath.stem}_{timestamp}{filepath.suffix}"
    quarantine_path = QUARANTINE_DIR / quarantine_name

    # Move file
    filepath.rename(quarantine_path)

    # Write reason file
    reason_path = quarantine_path.with_suffix(".reason.txt")
    reason_path.write_text(f"Quarantined: {datetime.now().isoformat()}\nReason: {reason}\n")

    print(f"  Quarantined to: {quarantine_path}")


def generate_story(story_id: str, mood: str, theme: str | None = None) -> bool:
    """
    Generate a single story with retries and validation.
    Returns True if successful, False if all retries exhausted.
    """
    filename = f"parable_{story_id}_{mood}_5min_adult_trad.txt"
    filepath = STORIES_DIR / filename

    # Never overwrite existing files
    if filepath.exists():
        print(f"SKIP: {filename} already exists")
        return True

    # Use default theme if not specified
    if theme is None:
        theme = DEFAULT_THEMES.get(mood, mood)

    print(f"\n{'='*60}")
    print(f"Generating: {filename}")
    print(f"  Mood: {mood}")
    print(f"  Theme: {theme}")
    print(f"{'='*60}")

    prompt = PROMPT_TEMPLATE.format(mood=mood, theme=theme)

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"\n  Attempt {attempt}/{MAX_RETRIES}...")

        # Call Ollama
        raw_text, success = call_ollama(prompt)
        if not success:
            print("  Failed to get response from Ollama")
            continue

        # Process output (truncate at <END>)
        text, had_end_token = process_output(raw_text)

        if not had_end_token:
            print("  WARNING: <END> token not found - treating as validation failure")
            # Write to temp file for debugging
            temp_path = QUARANTINE_DIR / f"{filename}.no_end_token.txt"
            QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)
            temp_path.write_text(raw_text)
            continue

        # Validate
        word_count = count_words(text)
        print(f"  Word count: {word_count}")

        is_valid, errors = validate_story(text)

        if is_valid:
            print(f"  ✓ Validation passed")

            # Create header and save
            header = create_header(story_id, mood, word_count)
            final_content = header + "\n" + text + "\n"

            filepath.write_text(final_content)
            print(f"  ✓ Saved to: {filepath}")
            return True
        else:
            print(f"  ✗ Validation failed:")
            for error in errors:
                print(f"    - {error}")

            # Save failed attempt for debugging
            temp_path = QUARANTINE_DIR / f"{filename}.attempt{attempt}.txt"
            QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)
            temp_path.write_text(text)

    # All retries exhausted
    print(f"\n  ✗ FAILED: All {MAX_RETRIES} attempts exhausted for {filename}")
    return False


def generate_batch(start_id: int = 301):
    """Generate all 8 moods starting at the given ID."""
    moods = [
        "joyful", "weary", "anxious", "hurting",
        "neutral", "encouraging", "calm_peaceful", "brave_courage"
    ]

    results = {"success": [], "failed": []}

    for i, mood in enumerate(moods):
        story_id = str(start_id + i)
        success = generate_story(story_id, mood)

        if success:
            results["success"].append(f"parable_{story_id}_{mood}")
        else:
            results["failed"].append(f"parable_{story_id}_{mood}")

    # Summary
    print("\n" + "="*60)
    print("BATCH GENERATION COMPLETE")
    print("="*60)
    print(f"  Successful: {len(results['success'])}/{len(moods)}")
    print(f"  Failed: {len(results['failed'])}/{len(moods)}")

    if results["failed"]:
        print("\n  Failed stories:")
        for name in results["failed"]:
            print(f"    - {name}")
        print(f"\n  Check quarantine folder: {QUARANTINE_DIR}")
        return False

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate traditional adult stories using Gemma-7B"
    )
    parser.add_argument("--story-id", type=str, help="Story ID (e.g., 301)")
    parser.add_argument("--mood", type=str, help="Mood (joyful, weary, anxious, hurting, neutral, encouraging, calm_peaceful, brave_courage)")
    parser.add_argument("--theme", type=str, help="Optional theme override")
    parser.add_argument("--batch", action="store_true", help="Generate all 8 moods")
    parser.add_argument("--start-id", type=int, default=301, help="Starting ID for batch mode (default: 301)")

    args = parser.parse_args()

    # Ensure output directory exists
    STORIES_DIR.mkdir(parents=True, exist_ok=True)

    if args.batch:
        success = generate_batch(args.start_id)
        sys.exit(0 if success else 1)
    elif args.story_id and args.mood:
        success = generate_story(args.story_id, args.mood, args.theme)
        sys.exit(0 if success else 1)
    else:
        parser.print_help()
        print("\nExamples:")
        print("  python3 generate_story.py --story-id 301 --mood joyful")
        print("  python3 generate_story.py --batch --start-id 301")
        sys.exit(1)


if __name__ == "__main__":
    main()
