#!/usr/bin/env python3
"""
generate_traditional_story.py — Bible PAL Traditional Story Factory (B2)

Generates one Traditional Bible PAL story with:
  - 3 length variants (short / full / long)
  - 1 canonical reflection
  - 4 ElevenLabs audio files
  - metadata JSON
  - anchor registry update

All story/reflection prose is generated by OpenAI gpt-4.1 via the Responses API.
This script generates NO prose itself.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import sys
import time
import urllib.error
import urllib.request

# ── Constants ──────────────────────────────────────────────────────────────

LOCKED_RANGES = {
    "short": (300, 500),
    "full":  (501, 900),
    "long":  (901, 1500),
}

# Kid mode word count ranges (per kid_bedtime_contract.txt)
KID_LOCKED_RANGES = {
    "short": (250, 600),
    "full":  (601, 1200),
    "long":  (1201, 1800),
}

KID_REFLECTION_WORD_RANGE = (60, 120)
KID_MAX_REGEN = 5

# Kid bedtime story rules (from docs/prompts/kid_bedtime_contract.txt)
_KID_BEDTIME_RULES = (
    "\n\nKID BEDTIME STORY RULES (violations cause rejection):\n"
    "AUDIENCE: Children ages 5–9, bedtime audio listening context.\n"
    "TONE: Calm, gentle, soothing throughout. Warm and comforting. "
    "Never startling, tense, or suspenseful.\n\n"
    "FORBIDDEN CONTENT (ABSOLUTE — any occurrence causes rejection):\n"
    "- No peril, danger, threat, violence (even implied)\n"
    "- No terror, fear, scary elements, loud noises\n"
    "- No predator imagery (jaws, teeth, claws, devouring)\n"
    "- No death, dying, perishing\n"
    "- No punishment, retribution, wrath, judgment\n"
    "- No crowns, thrones, power rewards, characters becoming kings/rulers\n"
    "- No battles, wars, conflicts (even resolved ones)\n"
    "- No chasing, fleeing, escape sequences\n"
    "- No monsters, beasts, threatening creatures\n"
    "- No darkness as threatening (only as peaceful nighttime)\n"
    "- No separation anxiety (lost, abandoned, alone in danger)\n\n"
    "BIBLICAL ACCURACY:\n"
    "- Stay faithful to actual Bible narrative\n"
    "- Do NOT invent promotions, rewards, battles, or conflicts\n"
    "- Focus on gentle, faithful aspects of each story\n\n"
    "REQUIRED 5-PART STRUCTURE:\n"
    "1. PEACEFUL OPENING (10–15%): calm safe setting, warm sensory details\n"
    "2. GENTLE SITUATION (20–25%): story context without tension\n"
    "3. FAITH IN ACTION (25–30%): trust in God through gentle actions\n"
    "4. QUIET RESOLUTION (20–25%): peaceful natural resolution\n"
    "5. SOOTHING BEDTIME CLOSING (10–15%): transition to rest/sleep, "
    "drowsy imagery, characters at rest, sleep-invitation language\n\n"
    "SENTENCE STYLE: Short, simple sentences (average 12 words or fewer). "
    "No complex vocabulary. Gentle rhythm. Smooth, flowing language.\n\n"
    "PARENT TEST: Would a parent feel completely safe falling asleep while "
    "this plays for their child? If not, revise."
)

# Bedtime closing signal phrases — at least one must appear in final 20% of kid stories
BEDTIME_CLOSING_SIGNALS = [
    "closed their eyes", "closed his eyes", "closed her eyes",
    "fell asleep", "drifted to sleep", "drifted off",
    "fast asleep", "softly asleep", "sound asleep",
    "asleep",
    "sleeping", "slept",
    "resting", "rested",
    "tucked in", "snuggled", "curled up",
    "quiet night", "still night", "peaceful night",
    "stars twinkled", "stars blinked", "stars shone",
    "moonlight", "starlight",
    "cozy blanket", "warm blanket",
    "dreaming", "dreams",
    "yawned", "yawning",
    "goodnight", "good night",
    "eyelids", "drowsy", "sleepy",
]

# Hard rules appended to every Traditional story prompt.
# These explicitly ban the most common GPT-4.1 drift patterns.
_TRADITIONAL_HARD_RULES = (
    "\n\nTRADITIONAL HARD RULES (violations cause rejection):\n"
    "1. NO inner thoughts or emotions: never write what characters feel, "
    "think, hope, wonder, know, or trust internally. "
    "No 'in their hearts', 'every heart knows', 'uncertainty fades', "
    "'hearts rested', 'wide-eyed with trust', 'confidence settling', "
    "'felt a sense of', 'hoping that', 'knew in'.\n"
    "2. NO interpretive theology or commentary beyond the passage: "
    "do not explain God's character, motives, or judgments. "
    "No 'every judgment is wise', 'his words are a balm', "
    "'there is no bitterness in him', 'he calls us back', "
    "'when we stray'. Only state what the passage states.\n"
    "3. NO symbolism or figurative metaphor: no 'golden thread', "
    "'river of song', 'breathes with music', 'like an offering', "
    "'as if meeting an old friend'. Keep descriptions concrete.\n"
    "4. NO first-person testimony: no lines like 'I was a child once', "
    "'He formed my lungs', 'When I was lost, he called my name'. "
    "The story is third-person narrative of observable events.\n"
    "5. NO personal application, moralizing, or devotional language. "
    "This is a faithful retelling, not a sermon or meditation.\n"
    "6. ONLY write observable actions, settings, dialogue, and "
    "direct scripture lines. Characters walk, sing, gather, lift hands, "
    "bring offerings, enter gates. Describe what a bystander could SEE and HEAR.\n"
    "7. Output ONLY the story text. No titles, headings, separator lines (---), "
    "or meta-commentary."
)

SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are Bible PAL in Traditional mode, Classic (KJV-style) lane. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use elevated, reverent KJV-like cadence and diction (Classic), "
        "but stay clear and comprehensible. "
        "Poetic style: Tier 3 (Elevated) — rich poetic language, complex rhythm. "
        "Meaning must remain scripture-accurate."
        + _TRADITIONAL_HARD_RULES
    ),
    "web": (
        "You are Bible PAL in Traditional mode, Modern (WEB-style) lane. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use clear, warm modern English in the style of the World English Bible (WEB). "
        "Poetic style: Tier 2 (Vivid+) — moderate sensory detail, warm imagery, "
        "clarity first. Favor concrete images over abstract flourishes. "
        "If a phrase feels literary rather than natural, pull back. "
        "Meaning must remain scripture-accurate."
        + _TRADITIONAL_HARD_RULES
    ),
}

SYSTEM_PROMPT_REFLECTION = (
    "You are Bible PAL creating a post-story reflection. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions ('you should', 'you must', 'try to'). "
    "Do not make diagnostic claims ('you are feeling'). "
    "Do not promise outcomes ('this will help you'). "
    "Do not use therapeutic language. "
    "Gently connect the story's themes to everyday life "
    "using pattern-based language (observations, invitations to notice), "
    "without telling the listener what to do. "
    "Target length: 120 to 220 words."
)

SYSTEM_PROMPT_REFLECTION_QUESTION = (
    "You are Bible PAL generating an optional reflection question. "
    "Return ONLY the question text — one sentence, no preamble, no quotes. "
    "If you cannot produce a gentle, appropriate question, return an empty string. "
    "Rules: "
    "- Gentle, invitational, everyday-life phrasing. "
    "- Use forms like 'Have you ever…', 'Is there…', 'Where in your life…'. "
    "- NOT directive, NOT guilt-inducing, NOT therapeutic. "
    "- The listener is NOT expected to answer. "
    "- One question only, or empty string if uncertain."
)

REFLECTION_WORD_RANGE = (120, 220)

KID_SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are Bible PAL in Traditional mode, Classic lane, "
        "for CHILDREN ages 5–9 at bedtime. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use gentle, reverent language with a soft KJV-like cadence, "
        "but keep vocabulary simple and sentences short for young children. "
        "Meaning must remain scripture-accurate."
        + _KID_BEDTIME_RULES
        + _TRADITIONAL_HARD_RULES
    ),
    "web": (
        "You are Bible PAL in Traditional mode, Modern (WEB-style) lane, "
        "for CHILDREN ages 5–9 at bedtime. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use clear, warm, simple modern English. "
        "Keep vocabulary accessible for young children. "
        "Meaning must remain scripture-accurate."
        + _KID_BEDTIME_RULES
        + _TRADITIONAL_HARD_RULES
    ),
}

KID_SYSTEM_PROMPT_REFLECTION = (
    "You are Bible PAL creating a post-story reflection "
    "for CHILDREN ages 5–9 at bedtime. "
    "Use simple, warm, gentle language a young child can understand. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions ('you should', 'you must', 'try to'). "
    "Do not make diagnostic claims. "
    "Do not use complex vocabulary. "
    "Gently connect the story's themes to a child's everyday life "
    "using simple observations and warm images. "
    "Keep sentences short (average 10 words). "
    "Target length: 60 to 120 words."
)

KID_SYSTEM_PROMPT_REFLECTION_QUESTION = (
    "You are Bible PAL generating an optional reflection question "
    "for CHILDREN ages 5–9. "
    "Return ONLY the question text — one simple sentence, "
    "no preamble, no quotes. "
    "If you cannot produce a gentle, age-appropriate question, "
    "return an empty string. "
    "Rules: "
    "- Simple words a 5-year-old can understand. "
    "- Warm, gentle, curious tone. "
    "- Use forms like 'Can you think of a time when…', "
    "'What is something…'. "
    "- NOT directive, NOT scary, NOT guilt-inducing. "
    "- One question only, or empty string if uncertain."
)

# Phrases banned from reflections (INVARIANTS.md)
REFLECTION_BANNED_PHRASES = [
    "you should", "you must", "you need to", "try to",
    "you are feeling", "this will help you", "this will make you",
    "healing", "coping", "therapy", "therapist", "counselor",
]

# ── Meta-text blocklist (ported from lib/safety/meta_text_validator.dart) ──
# Matched case-insensitively against the first ~200 chars of generated text.
META_TEXT_BLOCKLIST = [
    "here is", "here's", "this version", "certainly", "of course",
    "sure,", "sure!", "in this retelling", "expanded carefully",
    "staying true to", "the following", "this passage", "this story",
    "this verse", "this retelling", "this rendering", "this adaptation",
    "i've", "i have", "let me", "below is", "as requested", "as you asked",
    "happy to", "glad to", "i'd be", "i would be", "absolutely",
    "great question", "what a",
]

META_TEXT_MAX_REGEN = 3

META_TEXT_REPAIR_INSTRUCTION = (
    "YOUR OUTPUT WAS REJECTED — it contained meta-text (LLM preamble). "
    "FIX: Begin DIRECTLY with story/Scripture prose. "
    "No introductions, disclaimers, or meta-commentary. "
    "No 'Here is', 'Certainly', 'This version', etc. "
    "No '---' separator lines. "
    "Write ONLY the story content."
)


def check_meta_text(text: str) -> str | None:
    """Check for meta-text contamination in first ~200 chars.

    Returns the offending phrase if found, or None if clean.
    """
    trimmed = text.lstrip()
    if not trimmed:
        return "empty output"
    opening = trimmed[:200].lower()
    for phrase in META_TEXT_BLOCKLIST:
        if phrase in opening:
            return phrase
    # Also reject leading separator lines like "---"
    if trimmed.startswith("---") or trimmed.startswith("***"):
        return "leading separator"
    return None

# ── Traditional compliance validator ──────────────────────────────────────
# High-confidence phrase patterns that indicate Traditional rule violations.
# Matched case-insensitively against the full story text.
# Organized by violation category for clear error reporting.

TRADITIONAL_VIOLATIONS = {
    "INNER_THOUGHTS": [
        "in their hearts", "in his heart", "in her heart",
        "every heart knows", "every heart knew",
        "hearts rested", "heart rested",
        "hearts stirred", "heart stirred",
        "hearts swelled", "heart swelled",
        "uncertainty fades", "uncertainty faded",
        "confidence settling", "confidence settled",
        "wide-eyed with trust",
        "felt a sense of", "felt a wave of", "felt the warmth of",
        "knew in that moment", "knowing deep",
        "hoped that", "hoping that",
        "wondered if", "wondered what",
    ],
    "INTERPRETIVE_THEOLOGY": [
        "every judgment is wise",
        "every act is kindness",
        "his words are a balm",
        "there is no bitterness in him",
        "he calls us back",
        "when we stray",
        "no shadow of burden",
        "no shadow of doubt",
    ],
    "SYMBOLISM_METAPHOR": [
        "golden thread",
        "river of song",
        "breathes with music", "breathed with music",
        "house breathes", "house breathed",
        "like an offering",
        "as if meeting an old friend",
    ],
    "FIRST_PERSON_TESTIMONY": [
        "i was a child once",
        "he formed my lungs",
        "he called my name",
        "painted the features of my face",
        "when i was lost",
        "lifted up by his mercy",
    ],
}


def check_traditional_compliance(text: str) -> list[tuple[str, str]]:
    """Check story text for Traditional mode violations.

    Returns list of (category, phrase) tuples for each violation found.
    Empty list means compliant.
    """
    violations = []
    lower = text.lower()
    for category, phrases in TRADITIONAL_VIOLATIONS.items():
        for phrase in phrases:
            if phrase in lower:
                violations.append((category, phrase))
    return violations


def load_forbidden_words(root: pathlib.Path) -> list[str]:
    """Load forbidden words from server/kid_bedtime_forbidden.txt."""
    forbidden_file = root / "server" / "kid_bedtime_forbidden.txt"
    if not forbidden_file.exists():
        raise FileNotFoundError(f"Forbidden words file not found: {forbidden_file}")
    words = []
    for line in forbidden_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        words.append(line.lower())
    return words


def check_forbidden_words(text: str, forbidden: list[str]) -> list[str]:
    """Check text for forbidden kid-bedtime words.

    Returns list of forbidden words/phrases found. Empty list means clean.
    Multi-word phrases use substring matching.
    Single words use word-boundary matching to avoid false positives.
    """
    found = []
    lower = text.lower()
    for word in forbidden:
        if " " in word:
            # Multi-word phrase: substring match
            if word in lower:
                found.append(word)
        else:
            # Single word: word boundary match (e.g. "king" won't match "making")
            if re.search(r"\b" + re.escape(word) + r"\b", lower):
                found.append(word)
    return found


def check_bedtime_closing(text: str) -> bool:
    """Check that a kid story ends with bedtime closing signals.

    Returns True if at least one signal found in the last 20% of text.
    """
    words = text.split()
    if not words:
        return False
    cutoff = max(1, len(words) * 80 // 100)
    closing = " ".join(words[cutoff:]).lower()
    for signal in BEDTIME_CLOSING_SIGNALS:
        if signal in closing:
            return True
    return False


TRADITIONAL_SANITIZE_PROMPT = (
    "YOUR OUTPUT WAS REJECTED — it violates Traditional mode rules. "
    "Rewrite to fix ONLY the violations listed below. "
    "Keep the same passage structure, observable actions, setting details, "
    "and approximate length (±15%). Use 'Yahweh' naming. "
    "Replace inner thoughts with observable actions. "
    "Replace interpretive theology with direct scripture lines. "
    "Remove symbolism/metaphors and use concrete descriptions. "
    "Remove first-person testimony. "
    "Output ONLY the rewritten story — no notes, no analysis.\n\n"
    "VIOLATIONS FOUND:\n"
)


LANE_LABEL = {"kjv": "Classic (KJV-style)", "web": "Modern (WEB-style)"}
LANE_STYLE = {"kjv": "KJV", "web": "WEB"}

# 66-book Protestant canon — full unabbreviated English names
PROTESTANT_BOOKS = {
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
    "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles",
    "Ezra", "Nehemiah", "Esther", "Job", "Psalm", "Proverbs",
    "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
    "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah",
    "Haggai", "Zechariah", "Malachi",
    "Matthew", "Mark", "Luke", "John", "Acts", "Romans",
    "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
    "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians",
    "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews",
    "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John",
    "Jude", "Revelation",
}

# Matches: "Book Chapter" or "Book Chapter:Verse" or "Book Chapter:Verse–Verse"
# en-dash (–) required for verse ranges, not hyphen (-)
_ANCHOR_RE = re.compile(
    r"^(?P<book>.+?)\s+(?P<chapter>\d+)(?::(?P<verse>\d+)(?:\u2013(?P<verse_end>\d+))?)?$"
)


def validate_anchor_format(anchor: str) -> str | None:
    """Validate anchor against spec Section 2.2. Returns error message or None."""
    m = _ANCHOR_RE.match(anchor)
    if not m:
        return f"Anchor does not match format 'Book Chapter[:Verse[–Verse]]': {anchor!r}"
    book = m.group("book")
    if book not in PROTESTANT_BOOKS:
        return f"Unknown or abbreviated book name: {book!r} (must be full Protestant English name)"
    return None

# ── .env loader ────────────────────────────────────────────────────────────

def load_env(root: pathlib.Path) -> None:
    """Load .env from repo root safely.

    - Splits on first '=' only.
    - Strips whitespace from key and value.
    - Strips inline comments only when '#' is preceded by whitespace.
    - Assigns directly into os.environ (no setdefault).
    """
    env_file = root / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        # Strip inline comments: only when # is preceded by whitespace
        value = re.sub(r"\s+#.*$", "", value)
        os.environ[key.strip()] = value.strip()

# ── Retry helper ───────────────────────────────────────────────────────────

TRANSIENT_CODES = {429, 502, 503}
MAX_RETRIES = 3

def _urlopen_with_retry(req: urllib.request.Request, timeout: int):
    """urlopen with retry for transient HTTP errors (429/502/503/timeout).

    Non-transient errors (400, 401, 422, etc.) abort immediately.
    Up to MAX_RETRIES retries with exponential backoff (1s, 2s, 4s).
    """
    for attempt in range(MAX_RETRIES + 1):
        try:
            return urllib.request.urlopen(req, timeout=timeout)
        except urllib.error.HTTPError as exc:
            if exc.code in TRANSIENT_CODES and attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Transient HTTP {exc.code}, retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise
        except (urllib.error.URLError, TimeoutError) as exc:
            if attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Network error ({exc}), retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise

# ── OpenAI helper ──────────────────────────────────────────────────────────

def call_openai(system: str, user: str) -> str:
    """Call OpenAI Responses API with gpt-4.1. Returns output text."""
    api_key = os.environ["OPENAI_API_KEY"]
    payload = json.dumps({
        "model": "gpt-4.1",
        "input": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    }).encode()
    req = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    with _urlopen_with_retry(req, timeout=120) as resp:
        data = json.loads(resp.read())
    for output in data.get("output", []):
        if output.get("type") == "message":
            for content in output.get("content", []):
                if content.get("type") == "output_text":
                    return content["text"]
    raise RuntimeError(f"No text in OpenAI response: {json.dumps(data)[:500]}")

# ── ElevenLabs TTS helper ─────────────────────────────────────────────────

def tts(text: str, outfile: pathlib.Path, voice_id: str) -> None:
    """Generate TTS audio via ElevenLabs. Aborts if < 1000 bytes."""
    api_key = os.environ["ELEVENLABS_API_KEY"]
    payload = json.dumps({
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }).encode()
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
        data=payload,
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    with _urlopen_with_retry(req, timeout=300) as resp:
        audio = resp.read()
    if len(audio) < 1000:
        raise RuntimeError(
            f"Audio too small ({len(audio)} bytes) for {outfile.name}"
        )
    outfile.write_bytes(audio)

# ── Main pipeline ──────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Traditional Bible PAL story (B2)."
    )
    parser.add_argument("--story_id", type=int, required=True)
    parser.add_argument("--anchor", type=str, required=True,
                        help='Scripture anchor, e.g. "Psalm 23"')
    parser.add_argument("--mood", type=str, required=True,
                        help='e.g. peaceful, weary, hopeful')
    parser.add_argument("--lane", type=str, required=True,
                        choices=["web", "kjv"],
                        help="web = modern WEB style, kjv = classic KJV style")
    parser.add_argument("--voice_key", type=str, required=True,
                        help="Env var name, e.g. VOICE_JAMES_HUSKY")
    parser.add_argument("--batch", type=str,
                        default="PAL_TRADITIONAL_OPTION_B2",
                        help="Generation batch label")
    parser.add_argument("--kid", action="store_true",
                        help="Kid bedtime mode (ages 5-9, safe vocabulary)")
    args = parser.parse_args()

    sid = args.story_id
    lane = args.lane  # already lowercase via choices
    root = pathlib.Path(__file__).resolve().parents[2]  # repo root
    outdir = root / "assets" / "stories" / "traditional" / str(sid)
    anchors_file = root / "used_scripture_anchors.json"

    # ── Preflight ──────────────────────────────────────────────────────

    # 1. Load env
    load_env(root)

    # 2. Abort if output dir exists
    if outdir.exists():
        print(f"ABORT: output directory already exists: {outdir}")
        return 1

    # 3. Anchor registry
    if not anchors_file.exists():
        anchors_file.write_text("[]\n")
    anchors = json.loads(anchors_file.read_text())
    if args.anchor in anchors:
        print(f"ABORT: anchor already used: {args.anchor}")
        return 1

    # 3b. Anchor format validation (spec Section 2.2)
    anchor_err = validate_anchor_format(args.anchor)
    if anchor_err:
        print(f"ABORT: {anchor_err}")
        return 1

    # 4. Required env vars
    for var in ["OPENAI_API_KEY", "ELEVENLABS_API_KEY", args.voice_key]:
        val = os.environ.get(var, "").strip()
        if not val:
            print(f"ABORT: env var {var} is missing or empty")
            return 1

    # 5. Voice ID sanity
    voice_id = os.environ[args.voice_key].strip()
    if re.search(r"[\s\x00-\x1f]", voice_id):
        print(f"ABORT: voice ID contains whitespace or control chars: {voice_id!r}")
        return 1

    # ── Create output dir ──────────────────────────────────────────────
    outdir.mkdir(parents=True)
    print(f"Created {outdir}")

    def fail_clean(msg: str) -> int:
        print(f"FAIL: {msg}")
        shutil.rmtree(outdir, ignore_errors=True)
        print(f"Cleaned up {outdir}")
        return 1

    try:
        # ── Mode configuration ────────────────────────────────────────
        lane_label = LANE_LABEL[lane]
        is_kid = args.kid
        if is_kid:
            ranges = KID_LOCKED_RANGES
            max_regen = KID_MAX_REGEN
            system_story = KID_SYSTEM_PROMPTS_STORY[lane]
            refl_system = KID_SYSTEM_PROMPT_REFLECTION
            rq_system = KID_SYSTEM_PROMPT_REFLECTION_QUESTION
            refl_range = KID_REFLECTION_WORD_RANGE
            forbidden = load_forbidden_words(root)
            print(f"Kid bedtime mode: loaded {len(forbidden)} forbidden words, max retries {max_regen}")
        else:
            ranges = LOCKED_RANGES
            max_regen = META_TEXT_MAX_REGEN
            system_story = SYSTEM_PROMPTS_STORY[lane]
            refl_system = SYSTEM_PROMPT_REFLECTION
            rq_system = SYSTEM_PROMPT_REFLECTION_QUESTION
            refl_range = REFLECTION_WORD_RANGE
            forbidden = []

        # ── Generate stories ───────────────────────────────────────────
        for length, (lo, hi) in ranges.items():
            print(f"\n=== Generating {length.upper()} story ===")
            base_prompt = (
                f"Create a {length.upper()} Traditional Bible PAL story "
                f"retelling {args.anchor}. "
                f"HARD WORD COUNT: you MUST produce between {lo} and {hi} words. "
                f"This is a strict requirement — do not go under {lo} or over {hi}. "
            )
            if length == "short":
                base_prompt += (
                    "Build the scene with concrete, observable details — "
                    "setting, weather, sounds, physical actions — "
                    "to reach the required length. "
                    "Render the passage as a lived, narrated moment."
                )
            elif length == "full":
                base_prompt += (
                    "Expand detail and pacing: describe the setting, "
                    "the people, their physical actions, the sounds and sights. "
                    "Do not add new events beyond the passage."
                )
            else:  # long
                base_prompt += (
                    "Slow the narrative, enrich scene detail with "
                    "concrete sensory description (sights, sounds, textures). "
                    "Introduce no new events or meaning beyond the passage."
                )

            if is_kid:
                base_prompt += (
                    " This is a KID BEDTIME story for children ages 5–9. "
                    "Follow the required 5-part structure. "
                    "End with a soothing bedtime closing where characters "
                    "rest or sleep. "
                    "Use short, simple sentences (average 12 words). "
                    "AVOID these specific words (auto-rejected): "
                    "shadows, shadowy, darkness, alone, lonely, lost, "
                    "teeth, jaws, claws, sword, king, kingdom, throne, "
                    "crown, battle, enemy, death, dead, creature, "
                    "creatures, chase, chased, chasing, flee, escaped, "
                    "monster, beast, hunt. "
                    "Use peaceful alternatives: 'soft evening light', "
                    "'gentle twilight', 'quiet night', 'moonlight', "
                    "'together', 'safe and warm', 'living things'."
                )

            # Unified generation loop: meta-text + word count + Traditional compliance
            text = None
            for attempt in range(1, max_regen + 1):
                if attempt > 1:
                    print(f"  Fresh generation attempt {attempt}/{max_regen}...")

                text = call_openai(system_story, base_prompt)

                # Strip leading/trailing separator lines (---) that LLMs love to add
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                text = text.strip()

                # Gate 1: meta-text check
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Meta-text detected: {offending!r} (attempt {attempt})")
                    continue

                # Gate 2: word count
                wc = len(text.split())
                print(f"  Word count: {wc} (required: {lo}-{hi})")
                if wc < lo or wc > hi:
                    print(f"  Word count out of range (attempt {attempt})")
                    continue

                # Gate 3: Traditional compliance
                violations = check_traditional_compliance(text)
                if not violations:
                    # Gate 4 (kid only): forbidden words
                    if forbidden:
                        found_forbidden = check_forbidden_words(text, forbidden)
                        if found_forbidden:
                            print(f"  Forbidden words ({len(found_forbidden)}): {found_forbidden[:5]}")
                            continue
                    # Gate 5 (kid only): bedtime closing
                    if is_kid and not check_bedtime_closing(text):
                        print(f"  Missing bedtime closing signal (attempt {attempt})")
                        continue
                    break  # all gates passed

                print(f"  Traditional violations found ({len(violations)}):")
                for cat, phrase in violations:
                    print(f"    [{cat}] {phrase!r}")

                # Try one sanitize rewrite before burning another attempt
                violation_lines = "\n".join(
                    f"- [{cat}] \"{phrase}\"" for cat, phrase in violations
                )
                sanitize_prompt = (
                    TRADITIONAL_SANITIZE_PROMPT + violation_lines
                    + "\n\nORIGINAL STORY:\n" + text
                )
                print(f"  Attempting Traditional sanitize rewrite...")
                text = call_openai(system_story, sanitize_prompt)
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                text = text.strip()

                # Re-check all gates after sanitize
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Sanitize introduced meta-text: {offending!r}")
                    continue

                wc = len(text.split())
                print(f"  Post-sanitize word count: {wc} (required: {lo}-{hi})")
                if wc < lo or wc > hi:
                    print(f"  Post-sanitize word count out of range")
                    continue

                remaining = check_traditional_compliance(text)
                if remaining:
                    print(f"  Still {len(remaining)} violations after sanitize:")
                    for cat, phrase in remaining:
                        print(f"    [{cat}] {phrase!r}")
                    continue  # hard gate: retry fresh generation

                # Post-sanitize kid gates
                if forbidden:
                    found_forbidden = check_forbidden_words(text, forbidden)
                    if found_forbidden:
                        print(f"  Post-sanitize forbidden words ({len(found_forbidden)}): {found_forbidden[:5]}")
                        continue
                if is_kid and not check_bedtime_closing(text):
                    print(f"  Post-sanitize missing bedtime closing signal")
                    continue
                print(f"  Sanitize pass cleared all violations")
                break  # all gates passed
            else:
                return fail_clean(
                    f"{length} story failed all gates after "
                    f"{max_regen} attempts"
                )

            fname = f"story_{sid}_traditional_{lane}_{length}.txt"
            (outdir / fname).write_text(text)
            print(f"  Saved {fname}")

        # ── Generate reflection (B2: ONE) ──────────────────────────────
        print(f"\n=== Generating REFLECTION ===")
        if is_kid:
            refl_base_prompt = (
                f"Write one short reflection ({refl_range[0]} to {refl_range[1]} words) for a "
                f"kid bedtime {lane_label} story based on {args.anchor}. "
                f"Use simple, warm language a child ages 5–9 can understand. "
                f"Keep the tone gentle, soothing, and non-prescriptive."
            )
        else:
            refl_base_prompt = (
                f"Write one short reflection ({refl_range[0]} to {refl_range[1]} words) for a "
                f"Traditional {lane_label} story based on {args.anchor}. "
                f"Keep the tone reverent, gentle, and non-prescriptive."
            )

        reflection = None
        for attempt in range(1, max_regen + 1):
            refl_prompt = refl_base_prompt
            if attempt > 1:
                refl_prompt = META_TEXT_REPAIR_INSTRUCTION + "\n\n" + refl_base_prompt
                print(f"  Regeneration attempt {attempt}/{max_regen}...")

            reflection = call_openai(refl_system, refl_prompt)
            reflection = re.sub(r"^-{3,}\s*\n?", "", reflection.lstrip())
            reflection = re.sub(r"\n?-{3,}\s*$", "", reflection.rstrip())
            reflection = reflection.strip()

            # Gate 1: meta-text
            offending = check_meta_text(reflection)
            if offending is not None:
                print(f"  Meta-text detected in reflection: {offending!r} (attempt {attempt})")
                continue

            # Gate 2: word count
            refl_wc = len(reflection.split())
            print(f"  Reflection word count: {refl_wc} (target: {refl_range[0]}-{refl_range[1]})")
            if refl_wc < refl_range[0] or refl_wc > refl_range[1]:
                print(f"  Reflection word count out of range (attempt {attempt})")
                continue

            # Gate 3: banned phrases
            refl_lower = reflection.lower()
            banned_hit = None
            for phrase in REFLECTION_BANNED_PHRASES:
                if phrase in refl_lower:
                    banned_hit = phrase
                    break
            if banned_hit:
                print(f"  Reflection contains banned phrase: {banned_hit!r} (attempt {attempt})")
                continue

            # Gate 4 (kid only): forbidden words
            if forbidden:
                found_forbidden = check_forbidden_words(reflection, forbidden)
                if found_forbidden:
                    print(f"  Forbidden words in reflection: {found_forbidden[:5]} (attempt {attempt})")
                    continue

            break
        else:
            return fail_clean(
                f"Reflection failed gates after {max_regen} attempts"
            )

        refl_fname = f"reflection_{sid}_traditional_{lane}.txt"
        (outdir / refl_fname).write_text(reflection)
        print(f"  Saved {refl_fname} ({refl_wc} words)")

        # ── Generate reflection question (optional) ──────────────────
        print(f"\n=== Generating REFLECTION QUESTION ===")
        if is_kid:
            rq_prompt = (
                f"Generate one gentle, optional reflection question for a "
                f"kid bedtime {lane_label} story based on {args.anchor}. "
                f"Use simple words a child ages 5–9 can understand. "
                f"Return ONLY the question, or an empty string if none fits."
            )
        else:
            rq_prompt = (
                f"Generate one gentle, optional reflection question for a "
                f"Traditional {lane_label} story based on {args.anchor}. "
                f"The question should connect the story's theme to everyday life. "
                f"Return ONLY the question, or an empty string if none fits."
            )
        reflection_question = call_openai(rq_system, rq_prompt).strip()

        # Validate: must be 0 or 1 question (no multi-line)
        if "\n" in reflection_question:
            reflection_question = reflection_question.split("\n")[0].strip()

        # Validate banned phrases in question too
        rq_lower = reflection_question.lower()
        for phrase in REFLECTION_BANNED_PHRASES:
            if phrase in rq_lower:
                print(f"  Reflection question contained banned phrase {phrase!r}, clearing to empty")
                reflection_question = ""
                break

        # Kid mode: forbidden word check in question
        if reflection_question and forbidden:
            found_forbidden = check_forbidden_words(reflection_question, forbidden)
            if found_forbidden:
                print(f"  Reflection question contained forbidden words {found_forbidden[:3]}, clearing to empty")
                reflection_question = ""

        if reflection_question:
            print(f"  Reflection question: {reflection_question}")
        else:
            print(f"  Reflection question: (empty — none generated)")

        # ── Generate audio ─────────────────────────────────────────────
        print(f"\n=== Generating AUDIO ===")
        audio_map = [
            (f"story_{sid}_traditional_{lane}_short.txt",
             f"audio_{sid}_story_short.mp3"),
            (f"story_{sid}_traditional_{lane}_full.txt",
             f"audio_{sid}_story_full.mp3"),
            (f"story_{sid}_traditional_{lane}_long.txt",
             f"audio_{sid}_story_long.mp3"),
            (f"reflection_{sid}_traditional_{lane}.txt",
             f"audio_{sid}_reflection.mp3"),
        ]
        for txt_name, mp3_name in audio_map:
            print(f"  TTS: {txt_name} -> {mp3_name}")
            text = (outdir / txt_name).read_text()
            tts(text, outdir / mp3_name, voice_id)
            size = (outdir / mp3_name).stat().st_size
            print(f"    {size:,} bytes")

        # ── Write metadata ─────────────────────────────────────────────
        print(f"\n=== Writing metadata ===")
        meta = {
            "schemaVersion": 2,
            "storyId": sid,
            "mode": "traditional",
            "kidFriendly": is_kid,
            "languageStyle": LANE_STYLE[lane],
            "mood": args.mood,
            "scriptureAnchor": args.anchor,
            "lengths": ["short", "full", "long"],
            "voiceKey": args.voice_key,
            "createdByModel": "gpt-4.1",
            "generationBatch": args.batch,
            "reflectionQuestion": reflection_question,
            "files": {
                "short": {
                    "storyText": f"story_{sid}_traditional_{lane}_short.txt",
                    "storyAudio": f"audio_{sid}_story_short.mp3",
                },
                "full": {
                    "storyText": f"story_{sid}_traditional_{lane}_full.txt",
                    "storyAudio": f"audio_{sid}_story_full.mp3",
                },
                "long": {
                    "storyText": f"story_{sid}_traditional_{lane}_long.txt",
                    "storyAudio": f"audio_{sid}_story_long.mp3",
                },
                "reflection": {
                    "reflectionText": f"reflection_{sid}_traditional_{lane}.txt",
                    "reflectionAudio": f"audio_{sid}_reflection.mp3",
                },
            },
        }
        meta_fname = f"meta_{sid}.json"
        (outdir / meta_fname).write_text(json.dumps(meta, indent=2) + "\n")
        print(f"  Saved {meta_fname}")

        # ── Update anchor registry ─────────────────────────────────────
        print(f"\n=== Updating anchor registry ===")
        anchors.append(args.anchor)
        anchors.sort()
        anchors_file.write_text(json.dumps(anchors, indent=2) + "\n")
        print(f"  Anchors now: {anchors}")

    except Exception as exc:
        return fail_clean(str(exc))

    # ── Verification ───────────────────────────────────────────────────
    print(f"\n=== Verification ===")
    for f in sorted(outdir.iterdir()):
        size = f.stat().st_size
        extra = ""
        if f.suffix == ".txt" and "story" in f.name:
            extra = f" ({len(f.read_text().split())} words)"
        print(f"  {f.name}: {size:,} bytes{extra}")

    print(f"\nDONE. Story {sid} generated successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
