#!/usr/bin/env python3
"""
generate_traditional_story.py — Bible PAL Traditional Story Factory (B2)

Generates one Traditional Bible PAL story with:
  - 3 length variants (short / full / long)
  - 1 canonical reflection
  - 4 ElevenLabs audio files
  - metadata JSON
  - anchor registry update

All story/reflection prose is generated by OpenAI gpt-4.1 via the Responses API.
This script generates NO prose itself.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import sys
import time
import urllib.error
import urllib.request

# ── Constants ──────────────────────────────────────────────────────────────

LOCKED_RANGES = {
    "short": (300, 500),
    "full":  (501, 900),
    "long":  (901, 1500),
}

SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are Bible PAL in Traditional mode, Classic (KJV-style) lane. "
        "Retell real Bible passages faithfully. "
        "Do not add interpretation, symbolism, inner monologue, or added theology. "
        "Do not invent events beyond the passage. "
        "Use elevated, reverent KJV-like cadence and diction (Classic), "
        "but stay clear and comprehensible. "
        "Only describe observable events and spoken words. "
        "Poetic lift is allowed, but meaning must remain scripture-accurate."
    ),
    "web": (
        "You are Bible PAL in Traditional mode, Modern (WEB-style) lane. "
        "Retell real Bible passages faithfully. "
        "Do not add interpretation, symbolism, inner monologue, or added theology. "
        "Do not invent events beyond the passage. "
        "Use clear, warm modern English in the style of the World English Bible (WEB), "
        "but stay comprehensible and natural. "
        "Only describe observable events and spoken words. "
        "Poetic lift is allowed, but meaning must remain scripture-accurate."
    ),
}

SYSTEM_PROMPT_REFLECTION = (
    "You are Bible PAL creating a post-story reflection. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions. "
    "Gently connect the story's themes to everyday life "
    "using pattern-based language (observations, invitations to notice), "
    "without telling the listener what to do."
)

LANE_LABEL = {"kjv": "Classic (KJV-style)", "web": "Modern (WEB-style)"}
LANE_STYLE = {"kjv": "KJV", "web": "WEB"}

# 66-book Protestant canon — full unabbreviated English names
PROTESTANT_BOOKS = {
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
    "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles",
    "Ezra", "Nehemiah", "Esther", "Job", "Psalm", "Proverbs",
    "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
    "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah",
    "Haggai", "Zechariah", "Malachi",
    "Matthew", "Mark", "Luke", "John", "Acts", "Romans",
    "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
    "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians",
    "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews",
    "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John",
    "Jude", "Revelation",
}

# Matches: "Book Chapter" or "Book Chapter:Verse" or "Book Chapter:Verse–Verse"
# en-dash (–) required for verse ranges, not hyphen (-)
_ANCHOR_RE = re.compile(
    r"^(?P<book>.+?)\s+(?P<chapter>\d+)(?::(?P<verse>\d+)(?:\u2013(?P<verse_end>\d+))?)?$"
)


def validate_anchor_format(anchor: str) -> str | None:
    """Validate anchor against spec Section 2.2. Returns error message or None."""
    m = _ANCHOR_RE.match(anchor)
    if not m:
        return f"Anchor does not match format 'Book Chapter[:Verse[–Verse]]': {anchor!r}"
    book = m.group("book")
    if book not in PROTESTANT_BOOKS:
        return f"Unknown or abbreviated book name: {book!r} (must be full Protestant English name)"
    return None

# ── .env loader ────────────────────────────────────────────────────────────

def load_env(root: pathlib.Path) -> None:
    """Load .env from repo root safely.

    - Splits on first '=' only.
    - Strips whitespace from key and value.
    - Strips inline comments only when '#' is preceded by whitespace.
    - Assigns directly into os.environ (no setdefault).
    """
    env_file = root / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        # Strip inline comments: only when # is preceded by whitespace
        value = re.sub(r"\s+#.*$", "", value)
        os.environ[key.strip()] = value.strip()

# ── Retry helper ───────────────────────────────────────────────────────────

TRANSIENT_CODES = {429, 502, 503}
MAX_RETRIES = 3

def _urlopen_with_retry(req: urllib.request.Request, timeout: int):
    """urlopen with retry for transient HTTP errors (429/502/503/timeout).

    Non-transient errors (400, 401, 422, etc.) abort immediately.
    Up to MAX_RETRIES retries with exponential backoff (1s, 2s, 4s).
    """
    for attempt in range(MAX_RETRIES + 1):
        try:
            return urllib.request.urlopen(req, timeout=timeout)
        except urllib.error.HTTPError as exc:
            if exc.code in TRANSIENT_CODES and attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Transient HTTP {exc.code}, retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise
        except (urllib.error.URLError, TimeoutError) as exc:
            if attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Network error ({exc}), retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise

# ── OpenAI helper ──────────────────────────────────────────────────────────

def call_openai(system: str, user: str) -> str:
    """Call OpenAI Responses API with gpt-4.1. Returns output text."""
    api_key = os.environ["OPENAI_API_KEY"]
    payload = json.dumps({
        "model": "gpt-4.1",
        "input": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    }).encode()
    req = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    with _urlopen_with_retry(req, timeout=120) as resp:
        data = json.loads(resp.read())
    for output in data.get("output", []):
        if output.get("type") == "message":
            for content in output.get("content", []):
                if content.get("type") == "output_text":
                    return content["text"]
    raise RuntimeError(f"No text in OpenAI response: {json.dumps(data)[:500]}")

# ── ElevenLabs TTS helper ─────────────────────────────────────────────────

def tts(text: str, outfile: pathlib.Path, voice_id: str) -> None:
    """Generate TTS audio via ElevenLabs. Aborts if < 1000 bytes."""
    api_key = os.environ["ELEVENLABS_API_KEY"]
    payload = json.dumps({
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }).encode()
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
        data=payload,
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    with _urlopen_with_retry(req, timeout=300) as resp:
        audio = resp.read()
    if len(audio) < 1000:
        raise RuntimeError(
            f"Audio too small ({len(audio)} bytes) for {outfile.name}"
        )
    outfile.write_bytes(audio)

# ── Main pipeline ──────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Traditional Bible PAL story (B2)."
    )
    parser.add_argument("--story_id", type=int, required=True)
    parser.add_argument("--anchor", type=str, required=True,
                        help='Scripture anchor, e.g. "Psalm 23"')
    parser.add_argument("--mood", type=str, required=True,
                        help='e.g. peaceful, weary, hopeful')
    parser.add_argument("--lane", type=str, required=True,
                        choices=["web", "kjv"],
                        help="web = modern WEB style, kjv = classic KJV style")
    parser.add_argument("--voice_key", type=str, required=True,
                        help="Env var name, e.g. VOICE_JAMES_HUSKY")
    parser.add_argument("--batch", type=str,
                        default="PAL_TRADITIONAL_OPTION_B2",
                        help="Generation batch label")
    args = parser.parse_args()

    sid = args.story_id
    lane = args.lane  # already lowercase via choices
    root = pathlib.Path(__file__).resolve().parents[2]  # repo root
    outdir = root / "assets" / "stories" / "traditional" / str(sid)
    anchors_file = root / "used_scripture_anchors.json"

    # ── Preflight ──────────────────────────────────────────────────────

    # 1. Load env
    load_env(root)

    # 2. Abort if output dir exists
    if outdir.exists():
        print(f"ABORT: output directory already exists: {outdir}")
        return 1

    # 3. Anchor registry
    if not anchors_file.exists():
        anchors_file.write_text("[]\n")
    anchors = json.loads(anchors_file.read_text())
    if args.anchor in anchors:
        print(f"ABORT: anchor already used: {args.anchor}")
        return 1

    # 3b. Anchor format validation (spec Section 2.2)
    anchor_err = validate_anchor_format(args.anchor)
    if anchor_err:
        print(f"ABORT: {anchor_err}")
        return 1

    # 4. Required env vars
    for var in ["OPENAI_API_KEY", "ELEVENLABS_API_KEY", args.voice_key]:
        val = os.environ.get(var, "").strip()
        if not val:
            print(f"ABORT: env var {var} is missing or empty")
            return 1

    # 5. Voice ID sanity
    voice_id = os.environ[args.voice_key].strip()
    if re.search(r"[\s\x00-\x1f]", voice_id):
        print(f"ABORT: voice ID contains whitespace or control chars: {voice_id!r}")
        return 1

    # ── Create output dir ──────────────────────────────────────────────
    outdir.mkdir(parents=True)
    print(f"Created {outdir}")

    def fail_clean(msg: str) -> int:
        print(f"FAIL: {msg}")
        shutil.rmtree(outdir, ignore_errors=True)
        print(f"Cleaned up {outdir}")
        return 1

    try:
        # ── Generate stories ───────────────────────────────────────────
        system_story = SYSTEM_PROMPTS_STORY[lane]
        lane_label = LANE_LABEL[lane]

        for length, (lo, hi) in LOCKED_RANGES.items():
            print(f"\n=== Generating {length.upper()} story ===")
            user_prompt = (
                f"Create a {length.upper()} ({lo} to {hi} words) "
                f"Traditional Bible PAL story retelling {args.anchor}. "
            )
            if length == "short":
                user_prompt += (
                    "Do not add events beyond the passage; "
                    "render it as a lived, narrated moment."
                )
            elif length == "full":
                user_prompt += (
                    "Expand detail and pacing without adding "
                    "new events beyond the passage."
                )
            else:  # long
                user_prompt += (
                    "Slow the narrative, enrich scene detail, "
                    "but introduce no new events or meaning beyond the passage."
                )

            text = call_openai(system_story, user_prompt)
            wc = len(text.split())
            print(f"  Word count: {wc} (required: {lo}-{hi})")

            if wc < lo or wc > hi:
                return fail_clean(
                    f"{length} story has {wc} words, "
                    f"outside locked range {lo}-{hi}"
                )

            fname = f"story_{sid}_traditional_{lane}_{length}.txt"
            (outdir / fname).write_text(text)
            print(f"  Saved {fname}")

        # ── Generate reflection (B2: ONE) ──────────────────────────────
        print(f"\n=== Generating REFLECTION ===")
        refl_prompt = (
            f"Write one short reflection (1 to 2 paragraphs) for a "
            f"Traditional {lane_label} story based on {args.anchor}. "
            f"Keep the tone reverent, gentle, and non-prescriptive."
        )
        reflection = call_openai(SYSTEM_PROMPT_REFLECTION, refl_prompt)
        refl_fname = f"reflection_{sid}_traditional_{lane}.txt"
        (outdir / refl_fname).write_text(reflection)
        print(f"  Saved {refl_fname} ({len(reflection.split())} words)")

        # ── Generate audio ─────────────────────────────────────────────
        print(f"\n=== Generating AUDIO ===")
        audio_map = [
            (f"story_{sid}_traditional_{lane}_short.txt",
             f"audio_{sid}_story_short.mp3"),
            (f"story_{sid}_traditional_{lane}_full.txt",
             f"audio_{sid}_story_full.mp3"),
            (f"story_{sid}_traditional_{lane}_long.txt",
             f"audio_{sid}_story_long.mp3"),
            (f"reflection_{sid}_traditional_{lane}.txt",
             f"audio_{sid}_reflection.mp3"),
        ]
        for txt_name, mp3_name in audio_map:
            print(f"  TTS: {txt_name} -> {mp3_name}")
            text = (outdir / txt_name).read_text()
            tts(text, outdir / mp3_name, voice_id)
            size = (outdir / mp3_name).stat().st_size
            print(f"    {size:,} bytes")

        # ── Write metadata ─────────────────────────────────────────────
        print(f"\n=== Writing metadata ===")
        meta = {
            "schemaVersion": 1,
            "storyId": sid,
            "mode": "traditional",
            "languageStyle": LANE_STYLE[lane],
            "mood": args.mood,
            "scriptureAnchor": args.anchor,
            "lengths": ["short", "full", "long"],
            "voiceKey": args.voice_key,
            "createdByModel": "gpt-4.1",
            "generationBatch": args.batch,
            "files": {
                "short": {
                    "storyText": f"story_{sid}_traditional_{lane}_short.txt",
                    "storyAudio": f"audio_{sid}_story_short.mp3",
                },
                "full": {
                    "storyText": f"story_{sid}_traditional_{lane}_full.txt",
                    "storyAudio": f"audio_{sid}_story_full.mp3",
                },
                "long": {
                    "storyText": f"story_{sid}_traditional_{lane}_long.txt",
                    "storyAudio": f"audio_{sid}_story_long.mp3",
                },
                "reflection": {
                    "reflectionText": f"reflection_{sid}_traditional_{lane}.txt",
                    "reflectionAudio": f"audio_{sid}_reflection.mp3",
                },
            },
        }
        meta_fname = f"meta_{sid}.json"
        (outdir / meta_fname).write_text(json.dumps(meta, indent=2) + "\n")
        print(f"  Saved {meta_fname}")

        # ── Update anchor registry ─────────────────────────────────────
        print(f"\n=== Updating anchor registry ===")
        anchors.append(args.anchor)
        anchors.sort()
        anchors_file.write_text(json.dumps(anchors, indent=2) + "\n")
        print(f"  Anchors now: {anchors}")

    except Exception as exc:
        return fail_clean(str(exc))

    # ── Verification ───────────────────────────────────────────────────
    print(f"\n=== Verification ===")
    for f in sorted(outdir.iterdir()):
        size = f.stat().st_size
        extra = ""
        if f.suffix == ".txt" and "story" in f.name:
            extra = f" ({len(f.read_text().split())} words)"
        print(f"  {f.name}: {size:,} bytes{extra}")

    print(f"\nDONE. Story {sid} generated successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
