#!/usr/bin/env python3
"""
generate_traditional_story.py — Bible PAL Traditional Story Factory (B2)

Generates one Traditional Bible PAL story with:
  - 3 length variants (short / full / long)
  - 1 canonical reflection
  - 4 ElevenLabs audio files
  - metadata JSON
  - anchor registry update

All story/reflection prose is generated by OpenAI gpt-4.1 via the Responses API.
This script generates NO prose itself.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import sys
import time
import urllib.error
import urllib.request

# ── Constants ──────────────────────────────────────────────────────────────

LOCKED_RANGES = {
    "short": (300, 500),
    "full":  (501, 900),
    "long":  (901, 1500),
}

# Hard rules appended to every Traditional story prompt.
# These explicitly ban the most common GPT-4.1 drift patterns.
_TRADITIONAL_HARD_RULES = (
    "\n\nTRADITIONAL HARD RULES (violations cause rejection):\n"
    "1. NO inner thoughts or emotions: never write what characters feel, "
    "think, hope, wonder, know, or trust internally. "
    "No 'in their hearts', 'every heart knows', 'uncertainty fades', "
    "'hearts rested', 'wide-eyed with trust', 'confidence settling', "
    "'felt a sense of', 'hoping that', 'knew in'.\n"
    "2. NO interpretive theology or commentary beyond the passage: "
    "do not explain God's character, motives, or judgments. "
    "No 'every judgment is wise', 'his words are a balm', "
    "'there is no bitterness in him', 'he calls us back', "
    "'when we stray'. Only state what the passage states.\n"
    "3. NO symbolism or figurative metaphor: no 'golden thread', "
    "'river of song', 'breathes with music', 'like an offering', "
    "'as if meeting an old friend'. Keep descriptions concrete.\n"
    "4. NO first-person testimony: no lines like 'I was a child once', "
    "'He formed my lungs', 'When I was lost, he called my name'. "
    "The story is third-person narrative of observable events.\n"
    "5. NO personal application, moralizing, or devotional language. "
    "This is a faithful retelling, not a sermon or meditation.\n"
    "6. ONLY write observable actions, settings, dialogue, and "
    "direct scripture lines. Characters walk, sing, gather, lift hands, "
    "bring offerings, enter gates. Describe what a bystander could SEE and HEAR.\n"
    "7. Output ONLY the story text. No titles, headings, separator lines (---), "
    "or meta-commentary."
)

SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are Bible PAL in Traditional mode, Classic (KJV-style) lane. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use elevated, reverent KJV-like cadence and diction (Classic), "
        "but stay clear and comprehensible. "
        "Poetic style: Tier 3 (Elevated) — rich poetic language, complex rhythm. "
        "Meaning must remain scripture-accurate."
        + _TRADITIONAL_HARD_RULES
    ),
    "web": (
        "You are Bible PAL in Traditional mode, Modern (WEB-style) lane. "
        "Retell real Bible passages faithfully as observable-scene narrative. "
        "Use clear, warm modern English in the style of the World English Bible (WEB). "
        "Poetic style: Tier 2 (Vivid+) — moderate sensory detail, warm imagery, "
        "clarity first. Favor concrete images over abstract flourishes. "
        "If a phrase feels literary rather than natural, pull back. "
        "Meaning must remain scripture-accurate."
        + _TRADITIONAL_HARD_RULES
    ),
}

SYSTEM_PROMPT_REFLECTION = (
    "You are Bible PAL creating a post-story reflection. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions ('you should', 'you must', 'try to'). "
    "Do not make diagnostic claims ('you are feeling'). "
    "Do not promise outcomes ('this will help you'). "
    "Do not use therapeutic language. "
    "Gently connect the story's themes to everyday life "
    "using pattern-based language (observations, invitations to notice), "
    "without telling the listener what to do. "
    "Target length: 120 to 220 words."
)

SYSTEM_PROMPT_REFLECTION_QUESTION = (
    "You are Bible PAL generating an optional reflection question. "
    "Return ONLY the question text — one sentence, no preamble, no quotes. "
    "If you cannot produce a gentle, appropriate question, return an empty string. "
    "Rules: "
    "- Gentle, invitational, everyday-life phrasing. "
    "- Use forms like 'Have you ever…', 'Is there…', 'Where in your life…'. "
    "- NOT directive, NOT guilt-inducing, NOT therapeutic. "
    "- The listener is NOT expected to answer. "
    "- One question only, or empty string if uncertain."
)

REFLECTION_WORD_RANGE = (120, 220)

# Phrases banned from reflections (INVARIANTS.md)
REFLECTION_BANNED_PHRASES = [
    "you should", "you must", "you need to", "try to",
    "you are feeling", "this will help you", "this will make you",
    "healing", "coping", "therapy", "therapist", "counselor",
]

# ── Meta-text blocklist (ported from lib/safety/meta_text_validator.dart) ──
# Matched case-insensitively against the first ~200 chars of generated text.
META_TEXT_BLOCKLIST = [
    "here is", "here's", "this version", "certainly", "of course",
    "sure,", "sure!", "in this retelling", "expanded carefully",
    "staying true to", "the following", "this passage", "this story",
    "this verse", "this retelling", "this rendering", "this adaptation",
    "i've", "i have", "let me", "below is", "as requested", "as you asked",
    "happy to", "glad to", "i'd be", "i would be", "absolutely",
    "great question", "what a",
]

META_TEXT_MAX_REGEN = 3

META_TEXT_REPAIR_INSTRUCTION = (
    "YOUR OUTPUT WAS REJECTED — it contained meta-text (LLM preamble). "
    "FIX: Begin DIRECTLY with story/Scripture prose. "
    "No introductions, disclaimers, or meta-commentary. "
    "No 'Here is', 'Certainly', 'This version', etc. "
    "No '---' separator lines. "
    "Write ONLY the story content."
)


def check_meta_text(text: str) -> str | None:
    """Check for meta-text contamination in first ~200 chars.

    Returns the offending phrase if found, or None if clean.
    """
    trimmed = text.lstrip()
    if not trimmed:
        return "empty output"
    opening = trimmed[:200].lower()
    for phrase in META_TEXT_BLOCKLIST:
        if phrase in opening:
            return phrase
    # Also reject leading separator lines like "---"
    if trimmed.startswith("---") or trimmed.startswith("***"):
        return "leading separator"
    return None

# ── Traditional compliance validator ──────────────────────────────────────
# High-confidence phrase patterns that indicate Traditional rule violations.
# Matched case-insensitively against the full story text.
# Organized by violation category for clear error reporting.

TRADITIONAL_VIOLATIONS = {
    "INNER_THOUGHTS": [
        "in their hearts", "in his heart", "in her heart",
        "every heart knows", "every heart knew",
        "hearts rested", "heart rested",
        "hearts stirred", "heart stirred",
        "hearts swelled", "heart swelled",
        "uncertainty fades", "uncertainty faded",
        "confidence settling", "confidence settled",
        "wide-eyed with trust",
        "felt a sense of", "felt a wave of", "felt the warmth of",
        "knew in that moment", "knowing deep",
        "hoped that", "hoping that",
        "wondered if", "wondered what",
    ],
    "INTERPRETIVE_THEOLOGY": [
        "every judgment is wise",
        "every act is kindness",
        "his words are a balm",
        "there is no bitterness in him",
        "he calls us back",
        "when we stray",
        "no shadow of burden",
        "no shadow of doubt",
    ],
    "SYMBOLISM_METAPHOR": [
        "golden thread",
        "river of song",
        "breathes with music", "breathed with music",
        "house breathes", "house breathed",
        "like an offering",
        "as if meeting an old friend",
    ],
    "FIRST_PERSON_TESTIMONY": [
        "i was a child once",
        "he formed my lungs",
        "he called my name",
        "painted the features of my face",
        "when i was lost",
        "lifted up by his mercy",
    ],
}


def check_traditional_compliance(text: str) -> list[tuple[str, str]]:
    """Check story text for Traditional mode violations.

    Returns list of (category, phrase) tuples for each violation found.
    Empty list means compliant.
    """
    violations = []
    lower = text.lower()
    for category, phrases in TRADITIONAL_VIOLATIONS.items():
        for phrase in phrases:
            if phrase in lower:
                violations.append((category, phrase))
    return violations


TRADITIONAL_SANITIZE_PROMPT = (
    "YOUR OUTPUT WAS REJECTED — it violates Traditional mode rules. "
    "Rewrite to fix ONLY the violations listed below. "
    "Keep the same passage structure, observable actions, setting details, "
    "and approximate length (±15%). Use 'Yahweh' naming. "
    "Replace inner thoughts with observable actions. "
    "Replace interpretive theology with direct scripture lines. "
    "Remove symbolism/metaphors and use concrete descriptions. "
    "Remove first-person testimony. "
    "Output ONLY the rewritten story — no notes, no analysis.\n\n"
    "VIOLATIONS FOUND:\n"
)


LANE_LABEL = {"kjv": "Classic (KJV-style)", "web": "Modern (WEB-style)"}
LANE_STYLE = {"kjv": "KJV", "web": "WEB"}

# 66-book Protestant canon — full unabbreviated English names
PROTESTANT_BOOKS = {
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
    "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles",
    "Ezra", "Nehemiah", "Esther", "Job", "Psalm", "Proverbs",
    "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
    "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah",
    "Haggai", "Zechariah", "Malachi",
    "Matthew", "Mark", "Luke", "John", "Acts", "Romans",
    "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
    "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians",
    "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews",
    "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John",
    "Jude", "Revelation",
}

# Matches: "Book Chapter" or "Book Chapter:Verse" or "Book Chapter:Verse–Verse"
# en-dash (–) required for verse ranges, not hyphen (-)
_ANCHOR_RE = re.compile(
    r"^(?P<book>.+?)\s+(?P<chapter>\d+)(?::(?P<verse>\d+)(?:\u2013(?P<verse_end>\d+))?)?$"
)


def validate_anchor_format(anchor: str) -> str | None:
    """Validate anchor against spec Section 2.2. Returns error message or None."""
    m = _ANCHOR_RE.match(anchor)
    if not m:
        return f"Anchor does not match format 'Book Chapter[:Verse[–Verse]]': {anchor!r}"
    book = m.group("book")
    if book not in PROTESTANT_BOOKS:
        return f"Unknown or abbreviated book name: {book!r} (must be full Protestant English name)"
    return None

# ── .env loader ────────────────────────────────────────────────────────────

def load_env(root: pathlib.Path) -> None:
    """Load .env from repo root safely.

    - Splits on first '=' only.
    - Strips whitespace from key and value.
    - Strips inline comments only when '#' is preceded by whitespace.
    - Assigns directly into os.environ (no setdefault).
    """
    env_file = root / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        # Strip inline comments: only when # is preceded by whitespace
        value = re.sub(r"\s+#.*$", "", value)
        os.environ[key.strip()] = value.strip()

# ── Retry helper ───────────────────────────────────────────────────────────

TRANSIENT_CODES = {429, 502, 503}
MAX_RETRIES = 3

def _urlopen_with_retry(req: urllib.request.Request, timeout: int):
    """urlopen with retry for transient HTTP errors (429/502/503/timeout).

    Non-transient errors (400, 401, 422, etc.) abort immediately.
    Up to MAX_RETRIES retries with exponential backoff (1s, 2s, 4s).
    """
    for attempt in range(MAX_RETRIES + 1):
        try:
            return urllib.request.urlopen(req, timeout=timeout)
        except urllib.error.HTTPError as exc:
            if exc.code in TRANSIENT_CODES and attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Transient HTTP {exc.code}, retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise
        except (urllib.error.URLError, TimeoutError) as exc:
            if attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"    Network error ({exc}), retry {attempt + 1}/{MAX_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise

# ── OpenAI helper ──────────────────────────────────────────────────────────

def call_openai(system: str, user: str) -> str:
    """Call OpenAI Responses API with gpt-4.1. Returns output text."""
    api_key = os.environ["OPENAI_API_KEY"]
    payload = json.dumps({
        "model": "gpt-4.1",
        "input": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    }).encode()
    req = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    with _urlopen_with_retry(req, timeout=120) as resp:
        data = json.loads(resp.read())
    for output in data.get("output", []):
        if output.get("type") == "message":
            for content in output.get("content", []):
                if content.get("type") == "output_text":
                    return content["text"]
    raise RuntimeError(f"No text in OpenAI response: {json.dumps(data)[:500]}")

# ── ElevenLabs TTS helper ─────────────────────────────────────────────────

def tts(text: str, outfile: pathlib.Path, voice_id: str) -> None:
    """Generate TTS audio via ElevenLabs. Aborts if < 1000 bytes."""
    api_key = os.environ["ELEVENLABS_API_KEY"]
    payload = json.dumps({
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }).encode()
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
        data=payload,
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    with _urlopen_with_retry(req, timeout=300) as resp:
        audio = resp.read()
    if len(audio) < 1000:
        raise RuntimeError(
            f"Audio too small ({len(audio)} bytes) for {outfile.name}"
        )
    outfile.write_bytes(audio)

# ── Main pipeline ──────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Traditional Bible PAL story (B2)."
    )
    parser.add_argument("--story_id", type=int, required=True)
    parser.add_argument("--anchor", type=str, required=True,
                        help='Scripture anchor, e.g. "Psalm 23"')
    parser.add_argument("--mood", type=str, required=True,
                        help='e.g. peaceful, weary, hopeful')
    parser.add_argument("--lane", type=str, required=True,
                        choices=["web", "kjv"],
                        help="web = modern WEB style, kjv = classic KJV style")
    parser.add_argument("--voice_key", type=str, required=True,
                        help="Env var name, e.g. VOICE_JAMES_HUSKY")
    parser.add_argument("--batch", type=str,
                        default="PAL_TRADITIONAL_OPTION_B2",
                        help="Generation batch label")
    args = parser.parse_args()

    sid = args.story_id
    lane = args.lane  # already lowercase via choices
    root = pathlib.Path(__file__).resolve().parents[2]  # repo root
    outdir = root / "assets" / "stories" / "traditional" / str(sid)
    anchors_file = root / "used_scripture_anchors.json"

    # ── Preflight ──────────────────────────────────────────────────────

    # 1. Load env
    load_env(root)

    # 2. Abort if output dir exists
    if outdir.exists():
        print(f"ABORT: output directory already exists: {outdir}")
        return 1

    # 3. Anchor registry
    if not anchors_file.exists():
        anchors_file.write_text("[]\n")
    anchors = json.loads(anchors_file.read_text())
    if args.anchor in anchors:
        print(f"ABORT: anchor already used: {args.anchor}")
        return 1

    # 3b. Anchor format validation (spec Section 2.2)
    anchor_err = validate_anchor_format(args.anchor)
    if anchor_err:
        print(f"ABORT: {anchor_err}")
        return 1

    # 4. Required env vars
    for var in ["OPENAI_API_KEY", "ELEVENLABS_API_KEY", args.voice_key]:
        val = os.environ.get(var, "").strip()
        if not val:
            print(f"ABORT: env var {var} is missing or empty")
            return 1

    # 5. Voice ID sanity
    voice_id = os.environ[args.voice_key].strip()
    if re.search(r"[\s\x00-\x1f]", voice_id):
        print(f"ABORT: voice ID contains whitespace or control chars: {voice_id!r}")
        return 1

    # ── Create output dir ──────────────────────────────────────────────
    outdir.mkdir(parents=True)
    print(f"Created {outdir}")

    def fail_clean(msg: str) -> int:
        print(f"FAIL: {msg}")
        shutil.rmtree(outdir, ignore_errors=True)
        print(f"Cleaned up {outdir}")
        return 1

    try:
        # ── Generate stories ───────────────────────────────────────────
        system_story = SYSTEM_PROMPTS_STORY[lane]
        lane_label = LANE_LABEL[lane]

        for length, (lo, hi) in LOCKED_RANGES.items():
            print(f"\n=== Generating {length.upper()} story ===")
            base_prompt = (
                f"Create a {length.upper()} Traditional Bible PAL story "
                f"retelling {args.anchor}. "
                f"HARD WORD COUNT: you MUST produce between {lo} and {hi} words. "
                f"This is a strict requirement — do not go under {lo} or over {hi}. "
            )
            if length == "short":
                base_prompt += (
                    "Build the scene with concrete, observable details — "
                    "setting, weather, sounds, physical actions — "
                    "to reach the required length. "
                    "Render the passage as a lived, narrated moment."
                )
            elif length == "full":
                base_prompt += (
                    "Expand detail and pacing: describe the setting, "
                    "the people, their physical actions, the sounds and sights. "
                    "Do not add new events beyond the passage."
                )
            else:  # long
                base_prompt += (
                    "Slow the narrative, enrich scene detail with "
                    "concrete sensory description (sights, sounds, textures). "
                    "Introduce no new events or meaning beyond the passage."
                )

            # Unified generation loop: meta-text + word count + Traditional compliance
            text = None
            for attempt in range(1, META_TEXT_MAX_REGEN + 1):
                if attempt > 1:
                    print(f"  Fresh generation attempt {attempt}/{META_TEXT_MAX_REGEN}...")

                text = call_openai(system_story, base_prompt)

                # Strip leading/trailing separator lines (---) that LLMs love to add
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                text = text.strip()

                # Gate 1: meta-text check
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Meta-text detected: {offending!r} (attempt {attempt})")
                    continue

                # Gate 2: word count
                wc = len(text.split())
                print(f"  Word count: {wc} (required: {lo}-{hi})")
                if wc < lo or wc > hi:
                    print(f"  Word count out of range (attempt {attempt})")
                    continue

                # Gate 3: Traditional compliance
                violations = check_traditional_compliance(text)
                if not violations:
                    break  # all gates passed

                print(f"  Traditional violations found ({len(violations)}):")
                for cat, phrase in violations:
                    print(f"    [{cat}] {phrase!r}")

                # Try one sanitize rewrite before burning another attempt
                violation_lines = "\n".join(
                    f"- [{cat}] \"{phrase}\"" for cat, phrase in violations
                )
                sanitize_prompt = (
                    TRADITIONAL_SANITIZE_PROMPT + violation_lines
                    + "\n\nORIGINAL STORY:\n" + text
                )
                print(f"  Attempting Traditional sanitize rewrite...")
                text = call_openai(system_story, sanitize_prompt)
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                text = text.strip()

                # Re-check all gates after sanitize
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Sanitize introduced meta-text: {offending!r}")
                    continue

                wc = len(text.split())
                print(f"  Post-sanitize word count: {wc} (required: {lo}-{hi})")
                if wc < lo or wc > hi:
                    print(f"  Post-sanitize word count out of range")
                    continue

                remaining = check_traditional_compliance(text)
                if remaining:
                    print(f"  Still {len(remaining)} violations after sanitize:")
                    for cat, phrase in remaining:
                        print(f"    [{cat}] {phrase!r}")
                    continue  # hard gate: retry fresh generation

                print(f"  Sanitize pass cleared all violations")
                break  # all gates passed
            else:
                return fail_clean(
                    f"{length} story failed all gates after "
                    f"{META_TEXT_MAX_REGEN} attempts"
                )

            fname = f"story_{sid}_traditional_{lane}_{length}.txt"
            (outdir / fname).write_text(text)
            print(f"  Saved {fname}")

        # ── Generate reflection (B2: ONE) ──────────────────────────────
        print(f"\n=== Generating REFLECTION ===")
        refl_base_prompt = (
            f"Write one short reflection (120 to 220 words) for a "
            f"Traditional {lane_label} story based on {args.anchor}. "
            f"Keep the tone reverent, gentle, and non-prescriptive."
        )

        reflection = None
        for attempt in range(1, META_TEXT_MAX_REGEN + 1):
            refl_prompt = refl_base_prompt
            if attempt > 1:
                refl_prompt = META_TEXT_REPAIR_INSTRUCTION + "\n\n" + refl_base_prompt
                print(f"  Regeneration attempt {attempt}/{META_TEXT_MAX_REGEN}...")

            reflection = call_openai(SYSTEM_PROMPT_REFLECTION, refl_prompt)
            reflection = re.sub(r"^-{3,}\s*\n?", "", reflection.lstrip())
            reflection = re.sub(r"\n?-{3,}\s*$", "", reflection.rstrip())
            reflection = reflection.strip()

            offending = check_meta_text(reflection)
            if offending is None:
                break
            print(f"  Meta-text detected in reflection: {offending!r} (attempt {attempt})")
        else:
            return fail_clean(
                f"Reflection still has meta-text after {META_TEXT_MAX_REGEN} attempts"
            )

        refl_wc = len(reflection.split())
        print(f"  Reflection word count: {refl_wc} (target: {REFLECTION_WORD_RANGE[0]}-{REFLECTION_WORD_RANGE[1]})")

        if refl_wc < REFLECTION_WORD_RANGE[0] or refl_wc > REFLECTION_WORD_RANGE[1]:
            return fail_clean(
                f"Reflection has {refl_wc} words, "
                f"outside target range {REFLECTION_WORD_RANGE[0]}-{REFLECTION_WORD_RANGE[1]}"
            )

        # Validate reflection language safety
        refl_lower = reflection.lower()
        for phrase in REFLECTION_BANNED_PHRASES:
            if phrase in refl_lower:
                return fail_clean(
                    f"Reflection contains banned phrase: {phrase!r}"
                )

        refl_fname = f"reflection_{sid}_traditional_{lane}.txt"
        (outdir / refl_fname).write_text(reflection)
        print(f"  Saved {refl_fname} ({refl_wc} words)")

        # ── Generate reflection question (optional) ──────────────────
        print(f"\n=== Generating REFLECTION QUESTION ===")
        rq_prompt = (
            f"Generate one gentle, optional reflection question for a "
            f"Traditional {lane_label} story based on {args.anchor}. "
            f"The question should connect the story's theme to everyday life. "
            f"Return ONLY the question, or an empty string if none fits."
        )
        reflection_question = call_openai(
            SYSTEM_PROMPT_REFLECTION_QUESTION, rq_prompt
        ).strip()

        # Validate: must be 0 or 1 question (no multi-line)
        if "\n" in reflection_question:
            reflection_question = reflection_question.split("\n")[0].strip()

        # Validate banned phrases in question too
        rq_lower = reflection_question.lower()
        for phrase in REFLECTION_BANNED_PHRASES:
            if phrase in rq_lower:
                print(f"  Reflection question contained banned phrase {phrase!r}, clearing to empty")
                reflection_question = ""
                break

        if reflection_question:
            print(f"  Reflection question: {reflection_question}")
        else:
            print(f"  Reflection question: (empty — none generated)")

        # ── Generate audio ─────────────────────────────────────────────
        print(f"\n=== Generating AUDIO ===")
        audio_map = [
            (f"story_{sid}_traditional_{lane}_short.txt",
             f"audio_{sid}_story_short.mp3"),
            (f"story_{sid}_traditional_{lane}_full.txt",
             f"audio_{sid}_story_full.mp3"),
            (f"story_{sid}_traditional_{lane}_long.txt",
             f"audio_{sid}_story_long.mp3"),
            (f"reflection_{sid}_traditional_{lane}.txt",
             f"audio_{sid}_reflection.mp3"),
        ]
        for txt_name, mp3_name in audio_map:
            print(f"  TTS: {txt_name} -> {mp3_name}")
            text = (outdir / txt_name).read_text()
            tts(text, outdir / mp3_name, voice_id)
            size = (outdir / mp3_name).stat().st_size
            print(f"    {size:,} bytes")

        # ── Write metadata ─────────────────────────────────────────────
        print(f"\n=== Writing metadata ===")
        meta = {
            "schemaVersion": 2,
            "storyId": sid,
            "mode": "traditional",
            "languageStyle": LANE_STYLE[lane],
            "mood": args.mood,
            "scriptureAnchor": args.anchor,
            "lengths": ["short", "full", "long"],
            "voiceKey": args.voice_key,
            "createdByModel": "gpt-4.1",
            "generationBatch": args.batch,
            "reflectionQuestion": reflection_question,
            "files": {
                "short": {
                    "storyText": f"story_{sid}_traditional_{lane}_short.txt",
                    "storyAudio": f"audio_{sid}_story_short.mp3",
                },
                "full": {
                    "storyText": f"story_{sid}_traditional_{lane}_full.txt",
                    "storyAudio": f"audio_{sid}_story_full.mp3",
                },
                "long": {
                    "storyText": f"story_{sid}_traditional_{lane}_long.txt",
                    "storyAudio": f"audio_{sid}_story_long.mp3",
                },
                "reflection": {
                    "reflectionText": f"reflection_{sid}_traditional_{lane}.txt",
                    "reflectionAudio": f"audio_{sid}_reflection.mp3",
                },
            },
        }
        meta_fname = f"meta_{sid}.json"
        (outdir / meta_fname).write_text(json.dumps(meta, indent=2) + "\n")
        print(f"  Saved {meta_fname}")

        # ── Update anchor registry ─────────────────────────────────────
        print(f"\n=== Updating anchor registry ===")
        anchors.append(args.anchor)
        anchors.sort()
        anchors_file.write_text(json.dumps(anchors, indent=2) + "\n")
        print(f"  Anchors now: {anchors}")

    except Exception as exc:
        return fail_clean(str(exc))

    # ── Verification ───────────────────────────────────────────────────
    print(f"\n=== Verification ===")
    for f in sorted(outdir.iterdir()):
        size = f.stat().st_size
        extra = ""
        if f.suffix == ".txt" and "story" in f.name:
            extra = f" ({len(f.read_text().split())} words)"
        print(f"  {f.name}: {size:,} bytes{extra}")

    print(f"\nDONE. Story {sid} generated successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
