#!/usr/bin/env python3
"""
generate_creative_story.py — Bible PAL Creative Story Factory

Generates one Creative Bible PAL story with:
  - 3 length variants (short / full / long)
  - 1 canonical reflection
  - 4 ElevenLabs audio files
  - metadata JSON
  - theme registry update

All story/reflection prose is generated by Gemma 7B via Ollama (local).
This script generates NO prose itself.

Engine assignment: Creative = Gemma 7B via Ollama ONLY.
Forbidden: OpenAI API, cloud LLMs, external generators.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import sys
import time
import urllib.error
import urllib.request

# ── Constants ──────────────────────────────────────────────────────────────

LOCKED_RANGES = {
    "short": (200, 400),
    "full":  (401, 700),
    "long":  (701, 1100),
}

KID_LOCKED_RANGES = {
    "short": (200, 500),
    "full":  (501, 900),
    "long":  (901, 1400),
}

KID_REFLECTION_WORD_RANGE = (60, 120)
KID_MAX_REGEN = 5

# Ollama configuration
OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "gemma:7b"
TEMPERATURE = 0.7
STOP_TOKEN = "<END>"

# Token budget per length bucket.
# Gemma 7B tends to produce shorter outputs than cloud models,
# so budgets are generous (roughly 4-5× the target word count).
NUM_PREDICT = {
    "short": 1500,
    "full":  3000,
    "long":  6000,
}

MAX_REGEN = 5  # More attempts than traditional due to local model variability
MAX_CONTINUATIONS = 4  # Max continuation attempts per generation


# Kid safety rules (shared with traditional pipeline)
_KID_SAFETY_RULES = (
    "\n\nKID STORY RULES (violations cause rejection):\n"
    "AUDIENCE: Children ages 5–9, audio listening context.\n"
    "TONE: Calm, gentle, warm throughout. Comforting and encouraging. "
    "Never startling, tense, or suspenseful.\n\n"
    "FORBIDDEN CONTENT (ABSOLUTE — any occurrence causes rejection):\n"
    "- No peril, danger, threat, violence (even implied)\n"
    "- No terror, fear, scary elements, loud noises\n"
    "- No predator imagery (jaws, teeth, claws, devouring)\n"
    "- No death, dying, perishing\n"
    "- No punishment, retribution, wrath, judgment\n"
    "- No crowns, thrones, power rewards, characters becoming kings/rulers\n"
    "- No battles, wars, conflicts (even resolved ones)\n"
    "- No chasing, fleeing, escape sequences\n"
    "- No monsters, beasts, threatening creatures\n"
    "- No darkness as threatening (only as peaceful nighttime)\n"
    "- No separation anxiety (lost, abandoned, alone in danger)\n\n"
    "REQUIRED 5-PART STRUCTURE:\n"
    "1. PEACEFUL OPENING (10–15%): calm safe setting, warm sensory details\n"
    "2. GENTLE SITUATION (20–25%): story context without tension\n"
    "3. FAITH IN ACTION (25–30%): trust in God through gentle actions\n"
    "4. QUIET RESOLUTION (20–25%): peaceful natural resolution\n"
    "5. GENTLE, POSITIVE ENDING (10–15%): warm wrap-up, characters at "
    "peace, hopeful tone, sense of safety and comfort\n\n"
    "SENTENCE STYLE: Short, simple sentences (average 12 words or fewer). "
    "No complex vocabulary. Gentle rhythm. Smooth, flowing language.\n\n"
    "PARENT TEST: Would a parent feel completely safe having "
    "this play for their child at any time? If not, revise."
)

# Creative mode hard rules — the opposite of Traditional guardrails.
_CREATIVE_HARD_RULES = (
    "\n\nCREATIVE MODE HARD RULES (violations cause rejection):\n"
    "1. This is an ORIGINAL story with biblical themes. "
    "Do NOT retell a specific Bible story. Do NOT reference "
    "specific Bible characters by name (Jesus, Moses, David, Paul, etc.).\n"
    "2. NO scripture quoting or verse references. "
    "No 'as the Bible says', 'scripture tells us', 'the Word says'. "
    "No chapter/verse citations.\n"
    "3. NO teaching doctrine as fact. "
    "No 'God commands us to', 'the Lord requires'. "
    "Themes emerge through story, not instruction.\n"
    "4. NO God speaking directly as a character with dialogue. "
    "Faith can be shown through characters' actions and observations.\n"
    "5. NO spiritual authority claims. "
    "No 'this is truth', 'this is the way'.\n"
    "6. NO fear-based framing. No guilt, shame, or punishment motifs.\n"
    "7. NO advice, commands, or prescriptions to the listener. "
    "No 'you should', 'you must', 'remember to'.\n"
    "8. NO dependency language. No 'you need this', 'come back for more'.\n"
    "9. Output ONLY the story text. No titles, headings, separator lines (---), "
    "or meta-commentary.\n"
    "10. End your story with the token <END> and nothing else after it."
)

# Anti-repetition rules (shared across both engines)
_ANTI_REPETITION_RULES = (
    "\n\nANTI-REPETITION RULES (violations cause rejection):\n"
    "1. Do NOT repeat the same imagery (sky, light, sun, clouds, stars) "
    "more than twice in the entire story.\n"
    "2. Each section must advance time, setting, or emotional development. "
    "No section should feel interchangeable with another.\n"
    "3. Vary sentence openers — do NOT start 3+ consecutive sentences "
    "with the same word or structure.\n"
    "4. Do NOT restate the same sentiment (e.g. 'gentle', 'peaceful', 'safe') "
    "in similar phrasing across sections. Find fresh ways to convey tone.\n"
    "5. Avoid formulaic paragraph patterns (setup-detail-conclusion repeated "
    "identically across sections)."
)

SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are a warm, thoughtful storyteller creating original faith-inspired stories. "
        "Your stories explore biblical themes like grace, kindness, perseverance, "
        "forgiveness, and hope — but through fictional characters and modern or "
        "timeless settings. "
        "Use elevated, reverent KJV-like cadence and diction (Classic), "
        "but stay clear and comprehensible. "
        "Your stories should feel like parables — teaching through narrative, not instruction."
        + _CREATIVE_HARD_RULES
        + _ANTI_REPETITION_RULES
    ),
    "web": (
        "You are a warm, thoughtful storyteller creating original faith-inspired stories. "
        "Your stories explore biblical themes like grace, kindness, perseverance, "
        "forgiveness, and hope — but through fictional characters and modern or "
        "timeless settings. "
        "Use clear, warm modern English. "
        "Your stories should feel like parables — teaching through narrative, not instruction. "
        "Favor concrete images over abstract flourishes. "
        "If a phrase feels literary rather than natural, pull back."
        + _CREATIVE_HARD_RULES
        + _ANTI_REPETITION_RULES
    ),
}

SYSTEM_PROMPT_REFLECTION = (
    "You are creating a post-story reflection for an original faith-themed story. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions ('you should', 'you must', 'try to'). "
    "Do not make diagnostic claims ('you are feeling'). "
    "Do not promise outcomes ('this will help you'). "
    "Do not use therapeutic language. "
    "Gently connect the story's themes to everyday life "
    "using pattern-based language (observations, invitations to notice), "
    "without telling the listener what to do. "
    "Target length: 120 to 220 words. "
    "End with the token <END> and nothing else after it."
)

SYSTEM_PROMPT_REFLECTION_QUESTION = (
    "Generate an optional reflection question for a faith-themed story. "
    "Return ONLY the question text — one sentence, no preamble, no quotes. "
    "If you cannot produce a gentle, appropriate question, return an empty string. "
    "Rules: "
    "- Gentle, invitational, everyday-life phrasing. "
    "- Use forms like 'Have you ever…', 'Is there…', 'Where in your life…'. "
    "- NOT directive, NOT guilt-inducing, NOT therapeutic. "
    "- The listener is NOT expected to answer. "
    "- One question only, or empty string if uncertain. "
    "End with the token <END> and nothing else after it."
)

REFLECTION_WORD_RANGE = (120, 220)

KID_SYSTEM_PROMPTS_STORY = {
    "kjv": (
        "You are a gentle storyteller creating original faith-inspired stories "
        "for CHILDREN ages 5–9. "
        "Your stories explore themes like kindness, sharing, patience, "
        "and being helpful — through fictional characters in warm, safe settings. "
        "Use gentle, reverent language with a soft KJV-like cadence, "
        "but keep vocabulary simple and sentences short for young children."
        + _KID_SAFETY_RULES
        + _CREATIVE_HARD_RULES
        + _ANTI_REPETITION_RULES
    ),
    "web": (
        "You are a gentle storyteller creating original faith-inspired stories "
        "for CHILDREN ages 5–9. "
        "Your stories explore themes like kindness, sharing, patience, "
        "and being helpful — through fictional characters in warm, safe settings. "
        "Use clear, warm, simple modern English. "
        "Keep vocabulary accessible for young children."
        + _KID_SAFETY_RULES
        + _CREATIVE_HARD_RULES
        + _ANTI_REPETITION_RULES
    ),
}

KID_SYSTEM_PROMPT_REFLECTION = (
    "You are creating a post-story reflection for CHILDREN ages 5–9. "
    "Use simple, warm, gentle language a young child can understand. "
    "Do not give advice. "
    "Do not interpret theology. "
    "Do not prescribe actions ('you should', 'you must', 'try to'). "
    "Do not make diagnostic claims. "
    "Do not use complex vocabulary. "
    "Gently connect the story's themes to a child's everyday life "
    "using simple observations and warm images. "
    "Keep sentences short (average 10 words). "
    "Target length: 60 to 120 words. "
    "End with the token <END> and nothing else after it."
)

KID_SYSTEM_PROMPT_REFLECTION_QUESTION = (
    "Generate an optional reflection question "
    "for CHILDREN ages 5–9. "
    "Return ONLY the question text — one simple sentence, "
    "no preamble, no quotes. "
    "If you cannot produce a gentle, age-appropriate question, "
    "return an empty string. "
    "Rules: "
    "- Simple words a 5-year-old can understand. "
    "- Warm, gentle, curious tone. "
    "- Use forms like 'Can you think of a time when…', "
    "'What is something…'. "
    "- NOT directive, NOT scary, NOT guilt-inducing. "
    "- One question only, or empty string if uncertain. "
    "End with the token <END> and nothing else after it."
)

# Phrases banned from reflections (INVARIANTS.md)
REFLECTION_BANNED_PHRASES = [
    "you should", "you must", "you need to", "try to",
    "you are feeling", "this will help you", "this will make you",
    "healing", "coping", "therapy", "therapist", "counselor",
]

# ── Meta-text blocklist (shared with traditional pipeline) ──
META_TEXT_BLOCKLIST = [
    "here is", "here's", "this version", "certainly", "of course",
    "sure,", "sure!", "in this retelling", "expanded carefully",
    "staying true to", "the following", "this passage", "this story",
    "this verse", "this retelling", "this rendering", "this adaptation",
    "i've", "i have", "let me", "below is", "as requested", "as you asked",
    "happy to", "glad to", "i'd be", "i would be", "absolutely",
    "great question", "what a",
]

META_TEXT_REPAIR_INSTRUCTION = (
    "YOUR OUTPUT WAS REJECTED — it contained meta-text (LLM preamble). "
    "FIX: Begin DIRECTLY with story prose. "
    "No introductions, disclaimers, or meta-commentary. "
    "No 'Here is', 'Certainly', 'This version', etc. "
    "No '---' separator lines. "
    "Write ONLY the story content. End with <END>."
)

# ── Creative compliance validator ──────────────────────────────────────────
# Phrases that indicate a Creative story is drifting into Traditional territory
# or violating Creative mode rules.

CREATIVE_VIOLATIONS = {
    "SCRIPTURE_RETELLING": [
        "and jesus said", "and jesus spoke", "and jesus answered",
        "and moses said", "moses led the", "moses lifted",
        "and david said", "david picked up", "david took his",
        "and paul said", "paul wrote to",
        "and god said to", "the lord said to",
        "and the angel said",
    ],
    "SCRIPTURE_AUTHORITY": [
        "as the bible says", "as scripture says", "as it is written",
        "the word says", "the word of god says",
        "scripture tells us", "the bible tells us",
        "according to scripture", "in the book of",
        "chapter ", "verse ",
    ],
    "DIRECT_GOD_DIALOGUE": [
        "god said,", "god spoke,", "god replied,",
        "the lord said,", "the lord spoke,", "the lord replied,",
        "thus saith", "thus says the lord",
    ],
    "SPIRITUAL_COMMANDS": [
        "you should", "you must", "you need to",
        "remember to", "make sure you",
        "god commands", "the lord requires",
    ],
    "FEAR_FRAMING": [
        "you will be punished", "god will judge",
        "eternal damnation", "hellfire",
        "if you don't", "unless you repent",
    ],
}


def check_creative_compliance(text: str) -> list[tuple[str, str]]:
    """Check story text for Creative mode violations.

    Returns list of (category, phrase) tuples for each violation found.
    Empty list means compliant.
    """
    violations = []
    lower = text.lower()
    for category, phrases in CREATIVE_VIOLATIONS.items():
        for phrase in phrases:
            if phrase in lower:
                violations.append((category, phrase))
    return violations


def check_meta_text(text: str) -> str | None:
    """Check for meta-text contamination in first ~200 chars.

    Returns the offending phrase if found, or None if clean.
    """
    trimmed = text.lstrip()
    if not trimmed:
        return "empty output"
    opening = trimmed[:200].lower()
    for phrase in META_TEXT_BLOCKLIST:
        if phrase in opening:
            return phrase
    if trimmed.startswith("---") or trimmed.startswith("***"):
        return "leading separator"
    return None


def load_forbidden_words(root: pathlib.Path) -> list[str]:
    """Load forbidden words from server/kid_bedtime_forbidden.txt."""
    forbidden_file = root / "server" / "kid_bedtime_forbidden.txt"
    if not forbidden_file.exists():
        raise FileNotFoundError(f"Forbidden words file not found: {forbidden_file}")
    words = []
    for line in forbidden_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        words.append(line.lower())
    return words


def check_forbidden_words(text: str, forbidden: list[str]) -> list[str]:
    """Check text for forbidden kid-safety words.

    Multi-word phrases use substring matching.
    Single words use word-boundary matching to avoid false positives.
    """
    found = []
    lower = text.lower()
    for word in forbidden:
        if " " in word:
            if word in lower:
                found.append(word)
        else:
            if re.search(r"\b" + re.escape(word) + r"\b", lower):
                found.append(word)
    return found


# ── Kid-safe word replacements (deterministic post-processing) ────────
# Maps forbidden words to gentle alternatives for kid mode.
# Applied as whole-word replacements (case-preserving) before the
# forbidden-word gate. This is orchestration, not authoring.
KID_WORD_REPLACEMENTS = {
    "shadows": "shade",
    "shadowy": "dim",
    "shadow": "shade",
    "darkness": "nighttime",
    "creatures": "animals",
    "creature": "animal",
    "chased": "followed",
    "chase": "follow",
    "chasing": "following",
    "kingdom": "village",
    "king": "leader",
    "throne": "chair",
    "crown": "hat",
    "devoured": "ate happily",
    "devour": "enjoy",
    "abandoned": "left waiting",
    "stalk": "walk quietly",
    "stalked": "walked quietly",
    "fierce": "strong",
    "wicked": "unkind",
    "prey": "friend",
    "lurk": "wait",
    "lurking": "waiting",
    "prowl": "wander",
    "prowled": "wandered",
    "monster": "big helper",
    "beast": "animal",
    "sword": "tool",
    "battle": "challenge",
    "enemy": "stranger",
    "alone": "by themselves",
    "lonely": "quiet",
    "lost": "looking around",
    "escaped": "hurried away",
    "flee": "hurry away",
    "fled": "hurried away",
    "soldiers": "helpers",
    "lifeless": "still",
    "teeth": "smile",
    "jaws": "mouth",
    "claws": "paws",
    "hunt": "search",
    "danger": "surprise",
    "dangerous": "surprising",
    "terror": "worry",
    "death": "sleep",
    "dead": "still",
}


def apply_kid_word_replacements(text: str) -> str:
    """Apply deterministic kid-safe word replacements (case-preserving)."""
    for bad, good in KID_WORD_REPLACEMENTS.items():
        # Case-preserving whole-word replacement
        def _replace(m: re.Match) -> str:
            orig = m.group(0)
            if orig.isupper():
                return good.upper()
            if orig[0].isupper():
                return good[0].upper() + good[1:]
            return good
        text = re.sub(r"\b" + re.escape(bad) + r"\b", _replace, text, flags=re.IGNORECASE)
    return text


CREATIVE_SANITIZE_PROMPT = (
    "YOUR OUTPUT WAS REJECTED — it violates Creative mode rules. "
    "Rewrite to fix ONLY the violations listed below. "
    "Keep the same story structure, characters, setting, "
    "and approximate length (±15%). "
    "Remove all Bible character references — use fictional characters. "
    "Remove scripture quotes and verse references. "
    "Remove God speaking as a dialogue character. "
    "Remove any commands or prescriptions. "
    "Output ONLY the rewritten story — no notes, no analysis. "
    "End with <END>.\n\n"
    "VIOLATIONS FOUND:\n"
)

LANE_LABEL = {"kjv": "Classic (KJV-style)", "web": "Modern (WEB-style)"}
LANE_STYLE = {"kjv": "KJV", "web": "WEB"}


# ── .env loader ────────────────────────────────────────────────────────────

def load_env(root: pathlib.Path) -> None:
    """Load .env from repo root safely."""
    env_file = root / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = re.sub(r"\s+#.*$", "", value)
        os.environ[key.strip()] = value.strip()


# ── Ollama helper ──────────────────────────────────────────────────────────

def call_ollama(system: str, user: str, num_predict: int = 2400) -> str:
    """Call Ollama (Gemma 7B) locally. Returns generated text."""
    payload = json.dumps({
        "model": MODEL,
        "system": system,
        "prompt": user,
        "stream": False,
        "options": {
            "num_predict": num_predict,
            "temperature": TEMPERATURE,
        },
    }).encode()
    req = urllib.request.Request(
        OLLAMA_URL,
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            data = json.loads(resp.read())
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Ollama unreachable at {OLLAMA_URL}: {exc}") from exc

    text = data.get("response", "")
    if not text:
        raise RuntimeError(f"Empty response from Ollama: {json.dumps(data)[:500]}")

    # Strip <END> token and anything after it
    if STOP_TOKEN in text:
        text = text.split(STOP_TOKEN)[0]

    return text.strip()


# ── Retry helper for Ollama ───────────────────────────────────────────────

MAX_OLLAMA_RETRIES = 2

def call_ollama_with_retry(system: str, user: str, num_predict: int = 2400) -> str:
    """Call Ollama with retry for transient failures."""
    for attempt in range(MAX_OLLAMA_RETRIES + 1):
        try:
            return call_ollama(system, user, num_predict)
        except (RuntimeError, urllib.error.URLError, TimeoutError) as exc:
            if attempt < MAX_OLLAMA_RETRIES:
                wait = 2 ** attempt
                print(f"    Ollama error ({exc}), retry {attempt + 1}/{MAX_OLLAMA_RETRIES} in {wait}s...")
                time.sleep(wait)
                continue
            raise


# ── ElevenLabs TTS helper ─────────────────────────────────────────────────

def tts(text: str, outfile: pathlib.Path, voice_id: str) -> None:
    """Generate TTS audio via ElevenLabs. Aborts if < 1000 bytes."""
    api_key = os.environ["ELEVENLABS_API_KEY"]
    payload = json.dumps({
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }).encode()
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
        data=payload,
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    # Retry for transient HTTP errors
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                audio = resp.read()
            break
        except urllib.error.HTTPError as exc:
            if exc.code in {429, 502, 503} and attempt < 2:
                wait = 2 ** attempt
                print(f"    TTS transient HTTP {exc.code}, retry in {wait}s...")
                time.sleep(wait)
                continue
            raise
    if len(audio) < 1000:
        raise RuntimeError(
            f"Audio too small ({len(audio)} bytes) for {outfile.name}"
        )
    outfile.write_bytes(audio)


# ── Main pipeline ──────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Creative Bible PAL story (Gemma 7B via Ollama)."
    )
    parser.add_argument("--story_id", type=int, required=True)
    parser.add_argument("--theme", type=str, required=True,
                        help='Story theme, e.g. "finding joy in small kindnesses"')
    parser.add_argument("--mood", type=str, required=True,
                        help='e.g. joyful, weary, anxious, hurting, neutral')
    parser.add_argument("--lane", type=str, required=True,
                        choices=["web", "kjv"],
                        help="web = modern WEB style, kjv = classic KJV style")
    parser.add_argument("--voice_key", type=str, required=True,
                        help="Default env var name for voice, e.g. VOICE_JAMES_HUSKY")
    parser.add_argument("--voice_key_short", type=str, default=None,
                        help="Voice env var for SHORT story (overrides --voice_key)")
    parser.add_argument("--voice_key_full", type=str, default=None,
                        help="Voice env var for FULL story (overrides --voice_key)")
    parser.add_argument("--voice_key_long", type=str, default=None,
                        help="Voice env var for LONG story (overrides --voice_key)")
    parser.add_argument("--voice_key_reflection", type=str, default=None,
                        help="Voice env var for REFLECTION (overrides --voice_key)")
    parser.add_argument("--batch", type=str,
                        default="PAL_CREATIVE_BATCH_01",
                        help="Generation batch label")
    parser.add_argument("--kid", action="store_true",
                        help="Kid mode (ages 5-9, safe vocabulary)")
    parser.add_argument("--skip-audio", action="store_true",
                        help="Skip TTS audio generation (text only)")
    args = parser.parse_args()

    sid = args.story_id
    lane = args.lane
    root = pathlib.Path(__file__).resolve().parents[2]  # repo root
    outdir = root / "assets" / "stories" / "creative" / str(sid)
    themes_file = root / "used_creative_themes.json"

    # ── Preflight ──────────────────────────────────────────────────────

    # 1. Load env
    load_env(root)

    # 2. Abort if output dir exists
    if outdir.exists():
        print(f"ABORT: output directory already exists: {outdir}")
        return 1

    # 3. Theme registry (prevent duplicate mood+theme combos)
    if not themes_file.exists():
        themes_file.write_text("[]\n")
    themes = json.loads(themes_file.read_text())
    theme_key = f"{args.mood}:{args.theme}"
    if theme_key in themes:
        print(f"ABORT: theme already used for this mood: {theme_key}")
        return 1

    # 4. Build per-length voice map (override or fallback to default)
    voice_keys = {
        "short":      args.voice_key_short or args.voice_key,
        "full":       args.voice_key_full or args.voice_key,
        "long":       args.voice_key_long or args.voice_key,
        "reflection": args.voice_key_reflection or args.voice_key,
    }

    # 5. Required env vars
    required_vars = list(set(voice_keys.values()))
    if not args.skip_audio:
        required_vars.append("ELEVENLABS_API_KEY")
    for var in required_vars:
        val = os.environ.get(var, "").strip()
        if not val:
            print(f"ABORT: env var {var} is missing or empty")
            return 1

    # 6. Voice ID sanity for all voices
    voice_ids = {}
    for label, vk in voice_keys.items():
        vid = os.environ[vk].strip()
        if re.search(r"[\s\x00-\x1f]", vid):
            print(f"ABORT: voice ID for {label} ({vk}) contains whitespace or control chars: {vid!r}")
            return 1
        voice_ids[label] = vid
        if vk != args.voice_key or label == "short":
            print(f"  Voice [{label}]: {vk}")
    if len(set(voice_ids.values())) > 1:
        print(f"  Multi-voice mode: {len(set(voice_ids.values()))} distinct voices")

    # 7. Verify Ollama is reachable
    try:
        test_req = urllib.request.Request(
            "http://localhost:11434/api/tags",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(test_req, timeout=10) as resp:
            tags_data = json.loads(resp.read())
            models = [m.get("name", "") for m in tags_data.get("models", [])]
            if not any("gemma" in m.lower() for m in models):
                print(f"WARNING: Gemma model not found in Ollama. Available: {models}")
                print(f"  Run: ollama pull gemma:7b")
    except Exception as exc:
        print(f"ABORT: Ollama not reachable at {OLLAMA_URL}: {exc}")
        print(f"  Start Ollama: ollama serve")
        return 1

    # ── Create output dir ──────────────────────────────────────────────
    outdir.mkdir(parents=True)
    print(f"Created {outdir}")

    def fail_clean(msg: str) -> int:
        print(f"FAIL: {msg}")
        shutil.rmtree(outdir, ignore_errors=True)
        print(f"Cleaned up {outdir}")
        return 1

    try:
        # ── Mode configuration ────────────────────────────────────────
        lane_label = LANE_LABEL[lane]
        is_kid = args.kid
        if is_kid:
            ranges = KID_LOCKED_RANGES
            max_regen = KID_MAX_REGEN
            system_story = KID_SYSTEM_PROMPTS_STORY[lane]
            refl_system = KID_SYSTEM_PROMPT_REFLECTION
            rq_system = KID_SYSTEM_PROMPT_REFLECTION_QUESTION
            refl_range = KID_REFLECTION_WORD_RANGE
            forbidden = load_forbidden_words(root)
            print(f"Kid mode: loaded {len(forbidden)} forbidden words, max retries {max_regen}")
        else:
            ranges = LOCKED_RANGES
            max_regen = MAX_REGEN
            system_story = SYSTEM_PROMPTS_STORY[lane]
            refl_system = SYSTEM_PROMPT_REFLECTION
            rq_system = SYSTEM_PROMPT_REFLECTION_QUESTION
            refl_range = REFLECTION_WORD_RANGE
            forbidden = []

        # ── Generate stories ───────────────────────────────────────────
        for length, (lo, hi) in ranges.items():
            print(f"\n=== Generating {length.upper()} creative story ===")
            print(f"  Theme: {args.theme}")
            print(f"  Mood: {args.mood}")

            token_budget = NUM_PREDICT.get(length, 2400)

            base_prompt = (
                f"Create a {length.upper()} original faith-inspired story. "
                f"Theme: {args.theme}. "
                f"Mood: the story should resonate with someone feeling {args.mood}. "
                f"HARD WORD COUNT: you MUST produce between {lo} and {hi} words. "
                f"This is a strict requirement — do not go under {lo} or over {hi}. "
                f"Use fictional characters and settings. "
                f"Do NOT retell a Bible story. "
                f"Let faith themes emerge naturally through the narrative."
            )

            if length == "short":
                base_prompt += (
                    " Keep the story focused and intimate — "
                    "one character, one moment, one realization. "
                    "Build the scene with concrete details. "
                    f"Write at least {lo} words. Use multiple paragraphs."
                )
            elif length == "full":
                base_prompt += (
                    " Develop the characters and setting more fully. "
                    "Show the emotional arc through concrete scenes and actions. "
                    "Write a complete story with a beginning, middle, and end. "
                    f"You MUST write at least {lo} words — write many paragraphs, "
                    "each with 4-6 sentences. Take your time and develop the story fully."
                )
            else:  # long
                base_prompt += (
                    " This is a LONG story — take your time. "
                    "Structure: write AT LEAST 12 paragraphs, each paragraph "
                    "with 5-6 full sentences. "
                    "Develop the story in multiple scenes: "
                    "introduce the setting (2 paragraphs), "
                    "introduce the main character's situation (2 paragraphs), "
                    "develop the central challenge or journey (4 paragraphs), "
                    "show a turning point (2 paragraphs), "
                    "and provide a meaningful resolution (2 paragraphs). "
                    "Include rich sensory details — what characters see, hear, "
                    "smell, touch. Describe the environment in each scene. "
                    f"You MUST write at least {lo} words. "
                    "Do NOT rush to a conclusion. "
                    "Do NOT summarize — show every scene fully."
                )

            if is_kid:
                base_prompt += (
                    " This is a KID story for children ages 5–9. "
                    "Follow the required 5-part structure. "
                    "End with a gentle, positive closing that feels warm "
                    "and safe. "
                    "Use short, simple sentences (average 12 words). "
                    "AVOID these specific words (auto-rejected): "
                    "shadows, shadowy, darkness, alone, lonely, lost, "
                    "teeth, jaws, claws, sword, king, kingdom, throne, "
                    "crown, battle, enemy, death, dead, creature, "
                    "creatures, chase, chased, chasing, flee, escaped, "
                    "monster, beast, hunt, devoured, devour, stalk, "
                    "stalked, abandoned, fierce, wicked, prey, lurk, "
                    "lurking, prowl, prowled, danger, dangerous, terror. "
                    "Use gentle alternatives instead (shade instead of "
                    "shadows, village instead of kingdom, animals instead "
                    "of creatures, followed instead of chased)."
                )

            # Unified generation loop with continuation support
            text = None
            for attempt in range(1, max_regen + 1):
                if attempt > 1:
                    print(f"  Fresh generation attempt {attempt}/{max_regen}...")

                text = call_ollama_with_retry(system_story, base_prompt, token_budget)

                # Strip leading/trailing separators and markdown headings
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                # Strip leading markdown title lines (## Title, # Title, **Title**)
                text = re.sub(r"^#{1,3}\s+[^\n]+\n+", "", text.lstrip())
                text = re.sub(r"^\*\*[^\n]+\*\*\s*\n+", "", text.lstrip())
                text = text.strip()

                # Gate 1: meta-text check
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Meta-text detected: {offending!r} (attempt {attempt})")
                    continue

                # Gate 2: word count (with continuation for under-length)
                wc = len(text.split())
                print(f"  Word count: {wc} (required: {lo}-{hi})")

                # If under-length, try continuation before giving up
                if wc < lo and wc >= 100:
                    for cont in range(1, MAX_CONTINUATIONS + 1):
                        # Extract last 3 sentences for context
                        sentences = re.split(r'(?<=[.!?])\s+', text)
                        context = " ".join(sentences[-3:]) if len(sentences) >= 3 else text[-300:]
                        remaining = lo - wc
                        # Ask for 50% more than needed to account for Gemma under-producing
                        target_words = int(remaining * 1.5)
                        cont_prompt = (
                            f"You are continuing a story that is currently {wc} words long. "
                            f"The story MUST be at least {lo} words total. "
                            f"You need to write at least {remaining} more words "
                            f"(aim for {target_words} words in this continuation). "
                            f"Write {max(3, remaining // 80)} more paragraphs, "
                            f"each with 4-5 full sentences. "
                            f"Maintain the same tone, characters, and setting. "
                            f"Do NOT repeat what was already written. "
                            f"Do NOT rush to end the story — develop new scenes, "
                            f"add sensory details, show character interactions. "
                            f"Pick up naturally from where the story left off.\n\n"
                            f"STORY SO FAR (last part):\n...{context}\n\n"
                            f"CONTINUE THE STORY ({target_words}+ words, "
                            f"{max(3, remaining // 80)}+ paragraphs):"
                        )
                        print(f"  Continuation {cont}/{MAX_CONTINUATIONS} (need {remaining}+ more words)...")
                        continuation = call_ollama_with_retry(system_story, cont_prompt, token_budget)
                        continuation = re.sub(r"^-{3,}\s*\n?", "", continuation.lstrip())
                        continuation = re.sub(r"\n?-{3,}\s*$", "", continuation.rstrip())
                        continuation = re.sub(r"^#{1,3}\s+[^\n]+\n+", "", continuation.lstrip())
                        continuation = re.sub(r"^\*\*[^\n]+\*\*\s*\n+", "", continuation.lstrip())
                        continuation = continuation.strip()

                        # Merge: original + continuation
                        text = text + "\n\n" + continuation
                        wc = len(text.split())
                        print(f"  After continuation: {wc} words")
                        if wc >= lo:
                            break

                if wc < lo or wc > hi:
                    print(f"  Word count out of range (attempt {attempt})")
                    continue

                # Kid pre-processing: deterministic word replacements
                if is_kid:
                    text_before = text
                    text = apply_kid_word_replacements(text)
                    if text != text_before:
                        wc = len(text.split())
                        print(f"  Applied kid-safe word replacements (now {wc} words)")
                        # Re-check word count (replacements can change it)
                        if wc < lo or wc > hi:
                            print(f"  Word count shifted out of range after replacements")
                            continue

                # Gate 3: Creative compliance
                violations = check_creative_compliance(text)
                if not violations:
                    # Gate 4 (kid only): forbidden words
                    if forbidden:
                        found_forbidden = check_forbidden_words(text, forbidden)
                        if found_forbidden:
                            print(f"  Forbidden words ({len(found_forbidden)}): {found_forbidden[:5]}")
                            continue
                    break  # all gates passed

                print(f"  Creative violations found ({len(violations)}):")
                for cat, phrase in violations:
                    print(f"    [{cat}] {phrase!r}")

                # Try one sanitize rewrite before burning another attempt
                violation_lines = "\n".join(
                    f"- [{cat}] \"{phrase}\"" for cat, phrase in violations
                )
                sanitize_prompt = (
                    CREATIVE_SANITIZE_PROMPT + violation_lines
                    + "\n\nORIGINAL STORY:\n" + text
                )
                print(f"  Attempting Creative sanitize rewrite...")
                text = call_ollama_with_retry(system_story, sanitize_prompt, token_budget)
                text = re.sub(r"^-{3,}\s*\n?", "", text.lstrip())
                text = re.sub(r"\n?-{3,}\s*$", "", text.rstrip())
                text = text.strip()

                # Re-check all gates after sanitize
                offending = check_meta_text(text)
                if offending is not None:
                    print(f"  Sanitize introduced meta-text: {offending!r}")
                    continue

                wc = len(text.split())
                print(f"  Post-sanitize word count: {wc} (required: {lo}-{hi})")
                if wc < lo or wc > hi:
                    print(f"  Post-sanitize word count out of range")
                    continue

                remaining = check_creative_compliance(text)
                if remaining:
                    print(f"  Still {len(remaining)} violations after sanitize:")
                    for cat, phrase in remaining:
                        print(f"    [{cat}] {phrase!r}")
                    continue

                if forbidden:
                    found_forbidden = check_forbidden_words(text, forbidden)
                    if found_forbidden:
                        print(f"  Post-sanitize forbidden words ({len(found_forbidden)}): {found_forbidden[:5]}")
                        continue
                print(f"  Sanitize pass cleared all violations")
                break
            else:
                return fail_clean(
                    f"{length} story failed all gates after "
                    f"{max_regen} attempts"
                )

            fname = f"story_{sid}_creative_{lane}_{length}.txt"
            (outdir / fname).write_text(text)
            print(f"  Saved {fname}")

        # ── Generate reflection ──────────────────────────────────────
        print(f"\n=== Generating REFLECTION ===")
        if is_kid:
            refl_base_prompt = (
                f"Write one short reflection ({refl_range[0]} to {refl_range[1]} words) for a "
                f"kid-friendly {lane_label} story about '{args.theme}'. "
                f"Use simple, warm language a child ages 5–9 can understand. "
                f"Keep the tone gentle, encouraging, and non-prescriptive."
            )
        else:
            refl_base_prompt = (
                f"Write one short reflection ({refl_range[0]} to {refl_range[1]} words) for a "
                f"Creative {lane_label} story about '{args.theme}'. "
                f"Keep the tone warm, gentle, and non-prescriptive."
            )

        reflection = None
        for attempt in range(1, max_regen + 1):
            refl_prompt = refl_base_prompt
            if attempt > 1:
                refl_prompt = META_TEXT_REPAIR_INSTRUCTION + "\n\n" + refl_base_prompt
                print(f"  Regeneration attempt {attempt}/{max_regen}...")

            reflection = call_ollama_with_retry(refl_system, refl_prompt, 600)
            reflection = re.sub(r"^-{3,}\s*\n?", "", reflection.lstrip())
            reflection = re.sub(r"\n?-{3,}\s*$", "", reflection.rstrip())
            reflection = reflection.strip()

            # Gate 1: meta-text
            offending = check_meta_text(reflection)
            if offending is not None:
                print(f"  Meta-text in reflection: {offending!r} (attempt {attempt})")
                continue

            # Gate 2: word count
            refl_wc = len(reflection.split())
            print(f"  Reflection word count: {refl_wc} (target: {refl_range[0]}-{refl_range[1]})")
            if refl_wc < refl_range[0] or refl_wc > refl_range[1]:
                print(f"  Reflection word count out of range (attempt {attempt})")
                continue

            # Gate 3: banned phrases
            refl_lower = reflection.lower()
            banned_hit = None
            for phrase in REFLECTION_BANNED_PHRASES:
                if phrase in refl_lower:
                    banned_hit = phrase
                    break
            if banned_hit:
                print(f"  Reflection banned phrase: {banned_hit!r} (attempt {attempt})")
                continue

            # Kid pre-processing: deterministic word replacements for reflection
            if is_kid:
                reflection = apply_kid_word_replacements(reflection)
                refl_wc = len(reflection.split())

            # Gate 4 (kid only): forbidden words
            if forbidden:
                found_forbidden = check_forbidden_words(reflection, forbidden)
                if found_forbidden:
                    print(f"  Forbidden words in reflection: {found_forbidden[:5]} (attempt {attempt})")
                    continue

            break
        else:
            return fail_clean(
                f"Reflection failed gates after {max_regen} attempts"
            )

        refl_fname = f"reflection_{sid}_creative_{lane}.txt"
        (outdir / refl_fname).write_text(reflection)
        print(f"  Saved {refl_fname} ({refl_wc} words)")

        # ── Generate reflection question ──────────────────────────────
        print(f"\n=== Generating REFLECTION QUESTION ===")
        if is_kid:
            rq_prompt = (
                f"Generate one gentle, optional reflection question for a "
                f"kid-friendly {lane_label} story about '{args.theme}'. "
                f"Use simple words a child ages 5–9 can understand. "
                f"Return ONLY the question, or an empty string if none fits."
            )
        else:
            rq_prompt = (
                f"Generate one gentle, optional reflection question for a "
                f"Creative {lane_label} story about '{args.theme}'. "
                f"The question should connect the story's theme to everyday life. "
                f"Return ONLY the question, or an empty string if none fits."
            )
        reflection_question = call_ollama_with_retry(rq_system, rq_prompt, 200).strip()

        # Validate: must be 0 or 1 question
        if "\n" in reflection_question:
            reflection_question = reflection_question.split("\n")[0].strip()

        # Validate banned phrases in question
        rq_lower = reflection_question.lower()
        for phrase in REFLECTION_BANNED_PHRASES:
            if phrase in rq_lower:
                print(f"  Reflection question banned phrase {phrase!r}, clearing to empty")
                reflection_question = ""
                break

        # Kid mode: apply replacements then check forbidden words in question
        if reflection_question and is_kid:
            reflection_question = apply_kid_word_replacements(reflection_question)
        if reflection_question and forbidden:
            found_forbidden = check_forbidden_words(reflection_question, forbidden)
            if found_forbidden:
                print(f"  Reflection question forbidden words {found_forbidden[:3]}, clearing to empty")
                reflection_question = ""

        if reflection_question:
            print(f"  Reflection question: {reflection_question}")
        else:
            print(f"  Reflection question: (empty — none generated)")

        # ── Generate audio ─────────────────────────────────────────────
        if args.skip_audio:
            print(f"\n=== SKIPPING AUDIO (--skip-audio) ===")
        else:
            print(f"\n=== Generating AUDIO ===")
            audio_map = [
                (f"story_{sid}_creative_{lane}_short.txt",
                 f"audio_{sid}_story_short.mp3", "short"),
                (f"story_{sid}_creative_{lane}_full.txt",
                 f"audio_{sid}_story_full.mp3", "full"),
                (f"story_{sid}_creative_{lane}_long.txt",
                 f"audio_{sid}_story_long.mp3", "long"),
                (f"reflection_{sid}_creative_{lane}.txt",
                 f"audio_{sid}_reflection.mp3", "reflection"),
            ]
            for txt_name, mp3_name, length_key in audio_map:
                vid = voice_ids[length_key]
                vk = voice_keys[length_key]
                print(f"  TTS: {txt_name} -> {mp3_name} (voice: {vk})")
                audio_text = (outdir / txt_name).read_text()
                tts(audio_text, outdir / mp3_name, vid)
                size = (outdir / mp3_name).stat().st_size
                print(f"    {size:,} bytes")

        # ── Write metadata ─────────────────────────────────────────────
        print(f"\n=== Writing metadata ===")
        meta = {
            "schemaVersion": 2,
            "storyId": sid,
            "mode": "creative",
            "kidFriendly": is_kid,
            "languageStyle": LANE_STYLE[lane],
            "mood": args.mood,
            "theme": args.theme,
            "lengths": ["short", "full", "long"],
            "voiceKey": args.voice_key,
            "voiceKeys": voice_keys,
            "createdByModel": MODEL,
            "generationBatch": args.batch,
            "reflectionQuestion": reflection_question,
            "files": {
                "short": {
                    "storyText": f"story_{sid}_creative_{lane}_short.txt",
                    "storyAudio": f"audio_{sid}_story_short.mp3",
                },
                "full": {
                    "storyText": f"story_{sid}_creative_{lane}_full.txt",
                    "storyAudio": f"audio_{sid}_story_full.mp3",
                },
                "long": {
                    "storyText": f"story_{sid}_creative_{lane}_long.txt",
                    "storyAudio": f"audio_{sid}_story_long.mp3",
                },
                "reflection": {
                    "reflectionText": f"reflection_{sid}_creative_{lane}.txt",
                    "reflectionAudio": f"audio_{sid}_reflection.mp3",
                },
            },
        }
        meta_fname = f"meta_{sid}.json"
        (outdir / meta_fname).write_text(json.dumps(meta, indent=2) + "\n")
        print(f"  Saved {meta_fname}")

        # ── Update theme registry ─────────────────────────────────────
        print(f"\n=== Updating theme registry ===")
        themes.append(theme_key)
        themes.sort()
        themes_file.write_text(json.dumps(themes, indent=2) + "\n")
        print(f"  Themes now: {len(themes)} entries")

    except Exception as exc:
        return fail_clean(str(exc))

    # ── Verification ───────────────────────────────────────────────────
    print(f"\n=== Verification ===")
    for f in sorted(outdir.iterdir()):
        size = f.stat().st_size
        extra = ""
        if f.suffix == ".txt" and "story" in f.name:
            extra = f" ({len(f.read_text().split())} words)"
        print(f"  {f.name}: {size:,} bytes{extra}")

    print(f"\nDONE. Creative story {sid} generated successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
