import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// CRITICAL: Validates that no production story text files contain metadata
/// markers, debug text, or duplicate paragraphs that should not appear in
/// user-facing narration.
///
/// These patterns indicate LLM output leakage that was not sanitized by the
/// pipeline (sanitize_story_text in generate_v2_batch.sh).
void main() {
  group('CRITICAL: Story Text Sanitization', () {
    /// Metadata patterns that must NEVER appear in story text files.
    /// These are spoken aloud by the TTS narrator and must be stripped.
    final metadataPatterns = [
      RegExp(r'^[\s*]*[Ww]ord [Cc]ount[:\*]', multiLine: true),
      RegExp(r'^[\s*]*[Tt]otal [Ww]ords[:\*]', multiLine: true),
      RegExp(r'^[\s*]*[Aa]pproximate [Ww]ord [Cc]ount[:\*]', multiLine: true),
      RegExp(r'^\*\*[^*]+\*\*$', multiLine: true), // standalone bold header
      RegExp(r'^\*\*Title:\*\*', multiLine: true), // bold "Title:" prefix
      RegExp(r'^\s*\(source:', multiLine: true),
      RegExp(r'^\s*Story ID:', multiLine: true),
      RegExp(r'^\s*Model:', multiLine: true),
      RegExp(r'^\s*Generated by', multiLine: true),
    ];

    test('no story text files contain metadata markers', () {
      final storiesDir = Directory('assets/stories');
      expect(storiesDir.existsSync(), isTrue,
          reason: 'assets/stories directory must exist');

      final violations = <String>[];

      final storyFiles = storiesDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) =>
              f.path.contains('story_') &&
              f.path.endsWith('.txt') &&
              !f.path.contains('reflection_'));

      for (final file in storyFiles) {
        final content = file.readAsStringSync();
        final relativePath =
            file.path.replaceFirst(RegExp(r'^.*assets/stories/'), '');

        for (final pattern in metadataPatterns) {
          final match = pattern.firstMatch(content);
          if (match != null) {
            final matchedText = match.group(0)!.trim();
            violations.add('$relativePath: contains "$matchedText"');
          }
        }
      }

      expect(violations, isEmpty,
          reason:
              'Story text files must not contain metadata markers.\n'
              'These patterns are spoken aloud by the TTS narrator.\n'
              'Fix by running sanitize_story_text() or manually removing.');
    });

    test('no story text files contain consecutive duplicate paragraphs', () {
      final storiesDir = Directory('assets/stories');
      expect(storiesDir.existsSync(), isTrue);

      final violations = <String>[];

      final storyFiles = storiesDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) =>
              f.path.contains('story_') &&
              f.path.endsWith('.txt') &&
              !f.path.contains('reflection_'));

      for (final file in storyFiles) {
        final content = file.readAsStringSync();
        final relativePath =
            file.path.replaceFirst(RegExp(r'^.*assets/stories/'), '');

        // Split into paragraph blocks on blank lines
        final paragraphs = content
            .split(RegExp(r'\n\s*\n'))
            .map((p) => p.trim())
            .where((p) => p.isNotEmpty)
            .toList();

        for (int i = 1; i < paragraphs.length; i++) {
          if (paragraphs[i] == paragraphs[i - 1]) {
            final preview = paragraphs[i].length > 60
                ? '${paragraphs[i].substring(0, 60)}...'
                : paragraphs[i];
            violations.add(
                '$relativePath: duplicate paragraph at block $i: "$preview"');
          }
        }
      }

      expect(violations, isEmpty,
          reason:
              'Story text files must not contain consecutive duplicate paragraphs.\n'
              'This usually indicates a continuation artifact from the LLM.');
    });
  });
}
