#!/usr/bin/env python3
"""Extract the locked kid PAL reflection + transition lines (SPEC 51.7) from
their Dart source of truth into a generation manifest the audio batch script
reads.

The Dart const files are authoritative; this manifest is generated, never
hand-edited. Parses PalLineRef('ID', "text") entries directly so there is no
second copy of the line text to drift.

Usage:  python3 server/extract_kid_pal_lines.py
Output: server/kid_pal_lines_manifest.json
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFLECTION_SRC = ROOT / "lib/core/kid_pal_reflection_lines.dart"
TRANSITION_SRC = ROOT / "lib/core/kid_pal_transition_lines.dart"
OUT = ROOT / "server/kid_pal_lines_manifest.json"

# PalLineRef('KID_..._01', "the spoken text"). Text is double-quoted and (by the
# 51.7 ASCII rule) contains no double quotes or escapes, so this is exact.
PATTERN = re.compile(r"""PalLineRef\(\s*'([^']+)'\s*,\s*"([^"]*)"\s*\)""")


def extract(path):
    text = path.read_text(encoding="utf-8")
    pairs = [{"id": m.group(1), "text": m.group(2)} for m in PATTERN.finditer(text)]
    if not pairs:
        sys.exit(f"ERROR: no PalLineRef entries found in {path}")
    return pairs


def main():
    reflection = extract(REFLECTION_SRC)
    transition = extract(TRANSITION_SRC)

    manifest = {
        "description": (
            "Kid PAL reflection + transition line IDs + text for audio "
            "generation (SPEC 51.7). GENERATED by "
            "server/extract_kid_pal_lines.py from the Dart source of truth "
            "(lib/core/kid_pal_reflection_lines.dart, "
            "lib/core/kid_pal_transition_lines.dart). Do not hand-edit."
        ),
        "model": "eleven_v3",
        "reflection": reflection,
        "transition": transition,
    }

    OUT.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(
        f"Wrote {len(reflection)} reflection + {len(transition)} transition "
        f"lines to {OUT.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
